import type { FlagDef } from './args.js';

export interface CmdMeta {
  name: string;
  argv: string[];
  summary: string;
  usage: string;
  example: string;
  flags: FlagDef[];
  writes: boolean;
  /** Module loaded on demand, so `studio tools` never imports zod or an engine. */
  module:
    | 'tools'
    | 'project'
    | 'ops'
    | 'tl'
    | 'doctor'
    | 'ingest'
    | 'cache'
    | 'render'
    | 'inspect'
    | 'ui'
    | 'video'
    | 'audio'
    | 'image'
    | 'models'
    | 'motion'
    | 'captions'
    | 'mcp'
    | 'plugins'
    | 'expr'
    | 'script'
    | 'color'
    | 'design'
    | 'workspace'
    | 'fx'
    | 'track'
    | 'matte';
  fn: string;
}

const s = (name: string, desc: string, required = false): FlagDef => ({
  name,
  type: 'string',
  desc,
  required,
});
const n = (name: string, desc: string, required = false): FlagDef => ({
  name,
  type: 'number',
  desc,
  required,
});
const b = (name: string, desc: string): FlagDef => ({ name, type: 'boolean', desc });
const cmd = (c: Omit<CmdMeta, 'argv' | 'fn'> & { fn?: string }): CmdMeta => ({
  ...c,
  argv: c.name.split('.'),
  fn:
    c.fn ??
    c.name
      .split('.')
      .pop()!
      .replace(/-./g, (m) => m[1]!.toUpperCase()),
});

/** The single source of the command surface. `studio tools` is generated from this list. */
export const COMMANDS: CmdMeta[] = [
  cmd({
    name: 'tools',
    module: 'tools',
    writes: false,
    summary: 'List every implemented command with flags and an example.',
    usage: 'studio tools [--json]',
    example: 'studio tools',
    flags: [],
  }),
  cmd({
    name: 'doctor',
    module: 'doctor',
    writes: false,
    summary: 'Check node, ffmpeg, encoders (by test-encoding), disk, and models.',
    usage: 'studio doctor',
    example: 'studio doctor',
    flags: [],
  }),
  cmd({
    name: 'init',
    module: 'project',
    writes: true,
    summary: 'Create a project in the project directory.',
    usage: 'studio init <name> [--width N --height N --fps N --background #rrggbb]',
    example: 'studio init "Demo v2" --width 1920 --height 1080 --fps 30',
    flags: [
      n('width', 'canvas width'),
      n('height', 'canvas height'),
      n('fps', 'project frame rate'),
      s('background', 'sRGB hex'),
    ],
  }),
  cmd({
    name: 'ingest',
    module: 'ingest',
    writes: true,
    summary: 'Probe, hash, copy into assets/, register as assets; derive proxy, thumbnails, peaks.',
    usage: 'studio ingest <path...> [--sync] [--no-derive]',
    example: 'studio ingest ~/rec.mp4 --sync',
    flags: [
      b('sync', 'build proxy/thumbs/peaks now instead of in a background process'),
      b('no-derive', 'skip proxy/thumbs/peaks (run `studio cache build` later)'),
      s('label', 'log label'),
    ],
  }),
  cmd({
    name: 'cache.build',
    module: 'cache',
    writes: true,
    summary: 'Build missing proxy, thumbnails, and peaks (resumable; skips finished artifacts).',
    usage: 'studio cache build [--assets a_x,a_y]',
    example: 'studio cache build',
    flags: [s('assets', 'comma-separated asset ids (default: all)')],
  }),
  cmd({
    name: 'render',
    module: 'render',
    writes: true,
    summary:
      'Render the timeline: FFmpeg, or hybrid FFmpeg + motion renderer when composition clips exist (two-pass loudness, safe write, versioned name).',
    usage:
      'studio render [--preset ID] [--range A:B] [--preview] [--still MS] [--out NAME] [--explain]',
    example: 'studio render --preset youtube-1080p',
    flags: [
      s(
        'preset',
        'youtube-1080p (default), youtube-4k, vertical-1080x1920, square-1080, portrait-4x5, gif-small, overlay-alpha (composition clips only, transparent)',
      ),
      s('range', 'timeline range in ms, A:B'),
      b('preview', 'fast low-resolution render'),
      n('still', 'one PNG frame at this timeline ms'),
      s('out', 'output base name (default: <project>-<preset>-vN)'),
      s('encoder', 'video encoder (libx264 only for now)'),
      b('no-normalize', 'skip loudness normalization'),
      n('width', 'render at this width (height follows the aspect)'),
      {
        name: 'reframe',
        type: 'string',
        desc: 'fit (default), blur, center-crop',
        values: ['fit', 'blur', 'center-crop'],
      },
      s('x264-preset', 'x264 preset override, e.g. veryfast'),
      s('alpha-format', 'overlay-alpha only: prores4444 (default) or webm'),
      s('export', 'use preset and reframe from a recorded export id'),
      b('explain', 'print the plan and ffmpeg arguments, run nothing'),
    ],
  }),
  cmd({
    name: 'inspect.frame',
    module: 'inspect',
    writes: true,
    summary: "Extract PNG frames at times (ms). Also reports each frame's mean colour.",
    usage: 'studio inspect frame <file> --at MS[,MS...] [--width N]',
    example: 'studio inspect frame renders/demo-youtube-1080p-v1.mp4 --at 0,1500,4000',
    flags: [s('at', 'comma-separated times in ms', true), n('width', 'scale to this width')],
  }),
  cmd({
    name: 'inspect.sheet',
    module: 'inspect',
    writes: true,
    summary: 'Contact sheets, at most 24 tiles each, with tile times.',
    usage: 'studio inspect sheet <file> [--fps N] [--cols N] [--width N]',
    example: 'studio inspect sheet renders/demo-youtube-1080p-v1.mp4 --fps 1 --cols 6 --width 320',
    flags: [
      n('fps', 'tiles per second (default 1)'),
      n('cols', 'columns (default 6)'),
      n('width', 'tile width px (default 320)'),
    ],
  }),
  cmd({
    name: 'inspect.waveform',
    module: 'inspect',
    writes: true,
    summary: 'Waveform PNG of the audio.',
    usage: 'studio inspect waveform <file>',
    example: 'studio inspect waveform assets/vo.wav',
    flags: [],
  }),
  cmd({
    name: 'inspect.loudness',
    module: 'inspect',
    writes: false,
    summary: 'Integrated LUFS, LRA, true peak, sample peak, noise floor, clipping.',
    usage: 'studio inspect loudness <file> [--from MS] [--to MS]',
    example: 'studio inspect loudness renders/demo-youtube-1080p-v1.mp4',
    flags: [n('from', 'start of the window, ms'), n('to', 'end of the window, ms')],
  }),
  cmd({
    name: 'inspect.silence',
    module: 'inspect',
    writes: false,
    summary: 'Silent spans. Default threshold is the measured noise floor + 8 dB.',
    usage: 'studio inspect silence <file> [--noise-db N] [--min-s S]',
    example: 'studio inspect silence assets/talk.mp4 --min-s 0.4',
    flags: [
      n('noise-db', 'threshold in dB (default: noise floor + 8, between -50 and -20)'),
      n('min-s', 'minimum span in seconds (default 0.4)'),
    ],
  }),
  cmd({
    name: 'inspect.black',
    module: 'inspect',
    writes: false,
    summary: 'Black-frame spans (at least one frame) and frozen spans (at least 1 s).',
    usage: 'studio inspect black <file>',
    example: 'studio inspect black renders/demo-youtube-1080p-v1.mp4',
    flags: [],
  }),
  cmd({
    name: 'inspect.qc',
    module: 'inspect',
    writes: false,
    summary:
      'Technical QC with per-check pass/fail/warn/skipped and measured values. Exits 4 on any failure.',
    usage: 'studio inspect qc <file> [expectation flags]',
    example: 'studio inspect qc renders/demo-youtube-1080p-v1.mp4',
    flags: [
      n('width', 'expected width'),
      n('height', 'expected height'),
      n('fps', 'expected fps'),
      n('duration-ms', 'expected duration'),
      s('expect-audio', 'true|false'),
      n('target-lufs', 'loudness target'),
      n('true-peak-max', 'dBTP ceiling'),
      b('h264', 'check H.264 High/yuv420p/AAC-LC delivery'),
      s('joins', 'join times in ms, comma-separated'),
      s('planned-black', 'intended black/frozen ranges, A:B,A:B'),
      n('max-size-mb', 'file size budget'),
    ],
  }),
  cmd({
    name: 'ui',
    module: 'ui',
    writes: true,
    summary:
      'Serve the UI on localhost, push project changes to it, and accept its edits as ops (actor ui). Stop with Ctrl+C.',
    usage: 'studio ui [--port N] [--read-only] [--hub [--root DIR]]',
    example: 'studio ui --hub --root ~/edits',
    flags: [
      n('port', 'port (default 4173, 0 = any free port)'),
      b('read-only', 'refuse edits from the page'),
      b('hub', 'serve the media workspaces m1..m5 under <root>/workspaces, with a tab for each, instead of one project'),
      s('root', 'folder that holds workspaces/ (default: $STUDIO_ROOT or the project folder)'),
    ],
  }),
  cmd({
    name: 'video.cut-silence',
    module: 'video',
    fn: 'cutSilence',
    writes: true,
    summary:
      'Cut silences out of a clip (pauses are trimmed to the padding, never removed outright). Refuses above 40% removal without --yes.',
    usage:
      'studio video cut-silence --clip C [--noise-db N] [--min-s 0.4] [--pad-ms 100] [--yes] [--no-ripple]',
    example: 'studio video cut-silence --clip c_01 --dry-run',
    flags: [
      s('clip', 'clip id', true),
      n('noise-db', 'threshold in dB (default: measured noise floor + 8, clamped -50..-20)'),
      n('min-s', 'shortest silence to cut, seconds (default 0.4, not lower)'),
      n('pad-ms', 'pause kept next to speech (default 100)'),
      b('yes', 'allow removing more than 40% of the clip'),
      b('no-ripple', 'do not shift later clips on the track'),
    ],
  }),
  cmd({
    name: 'video.scenes',
    module: 'video',
    fn: 'scenes',
    writes: true,
    summary:
      'Scene-change candidates by FFmpeg scene score. Lists times; --apply adds markers (needs --clip). Never cuts.',
    usage: 'studio video scenes (--clip C | --asset A) [--threshold 0.3] [--apply]',
    example: 'studio video scenes --asset a_k3f9 --threshold 0.3',
    flags: [
      s('clip', 'clip id'),
      s('asset', 'asset id'),
      n('threshold', 'scene score 0..1 (default 0.3)'),
      b('apply', 'add timeline markers for each change'),
    ],
  }),
  cmd({
    name: 'video.speed',
    module: 'video',
    fn: 'speed',
    writes: true,
    summary:
      "Change a clip's playback speed. Audio is time-stretched (pitch kept) up to 8x, dropped above.",
    usage: 'studio video speed --clip C --factor F [--ripple]',
    example: 'studio video speed --clip c_03 --factor 4 --ripple',
    flags: [
      s('clip', 'clip id', true),
      n('factor', 'speed factor, 0.1 to 16 (above 1 is faster)', true),
      b('ripple', 'shift later clips on the track by the change in duration'),
    ],
  }),
  cmd({
    name: 'video.reframe',
    module: 'video',
    fn: 'reframe',
    writes: true,
    summary:
      'Record an export for another aspect ratio (fit, blur background, or center crop) and report what it costs.',
    usage:
      'studio video reframe --to vertical|square|portrait-4x5|youtube [--method fit|blur|center-crop] [--id ID] [--still MS]',
    example: 'studio video reframe --to vertical --method blur --still 3000',
    flags: [
      {
        name: 'to',
        type: 'string',
        desc: 'target aspect',
        required: true,
        values: ['vertical', 'square', 'portrait-4x5', 'youtube'],
      },
      {
        name: 'method',
        type: 'string',
        desc: 'how to fit (default fit)',
        values: ['fit', 'blur', 'center-crop'],
      },
      s('id', 'export id (default per target)'),
      n('still', 'also render a still at this timeline ms to check the framing'),
    ],
  }),
  cmd({
    name: 'audio.denoise',
    module: 'audio',
    fn: 'denoise',
    writes: true,
    summary: 'Add a high-pass and denoise to a clip; reports noise floor before and after.',
    usage:
      'studio audio denoise --clip C [--method afftdn|arnndn] [--nr 12] [--nf -50] [--hp 80] [--model FILE]',
    example: 'studio audio denoise --clip c_01 --nr 15',
    flags: [
      s('clip', 'clip id', true),
      {
        name: 'method',
        type: 'string',
        desc: 'afftdn (built in) or arnndn (needs --model)',
        values: ['afftdn', 'arnndn'],
      },
      n('nr', 'noise reduction dB (default 12)'),
      n('nf', 'noise floor dB (default -50)'),
      n('hp', 'high-pass Hz, 0 = none (default 80)'),
      s('model', 'RNNoise model file for arnndn'),
    ],
  }),
  cmd({
    name: 'audio.clean-podcast',
    module: 'audio',
    fn: 'cleanPodcast',
    writes: true,
    summary:
      'Podcast chain: high-pass, denoise, EQ, compressor, limiter, two-pass loudnorm. Prints the exact filtergraph and before/after numbers.',
    usage:
      'studio audio clean-podcast --clip C [--target -16] [--presence] [--no-denoise] [--no-eq] [--no-compress] [--no-normalize]',
    example: 'studio audio clean-podcast --clip c_01',
    flags: [
      s('clip', 'clip id', true),
      n('target', 'integrated LUFS (default -16)'),
      b('presence', 'add +2 dB at 3 kHz'),
      b('no-denoise', 'skip denoise'),
      b('no-eq', 'skip EQ'),
      b('no-compress', 'skip compressor'),
      b('no-normalize', 'skip loudnorm'),
    ],
  }),
  cmd({
    name: 'audio.normalize',
    module: 'audio',
    fn: 'normalize',
    writes: true,
    summary: 'Two-pass loudness normalization of one clip.',
    usage: 'studio audio normalize --clip C [--target -14] [--tp -1.5]',
    example: 'studio audio normalize --clip c_01 --target -16',
    flags: [
      s('clip', 'clip id', true),
      n('target', 'integrated LUFS (default -14)'),
      n('tp', 'true-peak ceiling dBTP (default -1.5)'),
    ],
  }),
  cmd({
    name: 'audio.duck',
    module: 'audio',
    fn: 'duck',
    writes: true,
    summary:
      'Duck a music clip under a voice track with a sidechain compressor; also sets the music bed about 20 dB under the voice.',
    usage:
      'studio audio duck --clip MUSIC --by VOICE_TRACK [--reduction 15] [--ratio 8] [--attack 20] [--release 400] [--music-offset-db -20] [--no-level]',
    example: 'studio audio duck --clip c_music --by t_a1',
    flags: [
      s('clip', 'music clip id', true),
      s('by', 'voice track id', true),
      n('reduction', 'target reduction under speech, dB (default 15)'),
      n('ratio', 'compression ratio (default 8)'),
      n('attack', 'attack ms (default 20)'),
      n('release', 'release ms (default 400)'),
      n('music-offset-db', 'music level relative to the voice (default -20)'),
      b('no-level', 'do not set the music level'),
    ],
  }),
  cmd({
    name: 'audio.sfx.add',
    module: 'audio',
    fn: 'sfxAdd',
    writes: true,
    summary: 'Add a music/SFX file to the local library index. A license note is required.',
    usage: 'studio audio sfx add <file> --tags a,b --license "NOTE" [--bpm N]',
    example: 'studio audio sfx add whoosh.wav --tags whoosh,transition --license "CC0"',
    flags: [
      s('tags', 'comma-separated tags'),
      s('license', 'license note, or "unknown" (required; checked by the command)'),
      n('bpm', 'tempo'),
      n('loop-start', 'loop start ms'),
      n('loop-end', 'loop end ms'),
    ],
  }),
  cmd({
    name: 'audio.sfx.search',
    module: 'audio',
    fn: 'sfxSearch',
    writes: false,
    summary: 'Search the library by file name and tags only.',
    usage: 'studio audio sfx search "<query>" [--limit N]',
    example: 'studio audio sfx search "calm piano"',
    flags: [n('limit', 'max results (default 10)')],
  }),
  cmd({
    name: 'audio.sfx.list',
    module: 'audio',
    fn: 'sfxList',
    writes: false,
    summary: 'List the library.',
    usage: 'studio audio sfx list',
    example: 'studio audio sfx list',
    flags: [],
  }),
  cmd({
    name: 'image.resize',
    module: 'image',
    fn: 'resize',
    writes: true,
    summary:
      'Resize or convert a few images. Lists the outputs. Never enlarges unless asked; strips metadata; converts to sRGB.',
    usage:
      'studio image resize <files|folders...> --width N [--height N] [--mode inside|cover|contain|fill] [--format webp]',
    example: 'studio image resize photo.jpg --width 1200 --format webp',
    flags: [
      n('width', 'target width px'),
      n('height', 'target height px'),
      {
        name: 'mode',
        type: 'string',
        desc: 'inside (default), cover, contain, fill',
        values: ['inside', 'cover', 'contain', 'fill'],
      },
      s('background', 'colour for contain and for flattening alpha, #rrggbb'),
      b('allow-enlarge', 'allow output larger than the source'),
      {
        name: 'format',
        type: 'string',
        desc: 'jpeg, webp, avif, png (default: keep jpeg/png/webp)',
        values: ['jpeg', 'webp', 'avif', 'png'],
      },
      n('quality', '1-100 (defaults: jpeg 82, webp 80, avif 50)'),
      b('sharpen', 'light unsharp after a downscale'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop (cover only)',
        values: ['attention', 'entropy'],
      },
      s('out-dir', 'output folder (default renders/images)'),
      n('concurrency', 'parallel images (default min(cores-1, 4))'),
      b('no-resume', 'reprocess everything'),
    ],
  }),
  cmd({
    name: 'image.batch',
    module: 'image',
    fn: 'batch',
    writes: true,
    summary:
      'Resize a folder of images with bounded memory, progress on stderr, and resume. Reports counts, failures, bytes, peak memory.',
    usage: 'studio image batch <folder...> --width N [--format webp] [--concurrency N]',
    example: 'studio image batch shots/ --width 1280 --format webp',
    flags: [
      n('width', 'target width px'),
      n('height', 'target height px'),
      {
        name: 'mode',
        type: 'string',
        desc: 'inside (default), cover, contain, fill',
        values: ['inside', 'cover', 'contain', 'fill'],
      },
      s('background', 'colour for contain and for flattening alpha, #rrggbb'),
      b('allow-enlarge', 'allow output larger than the source'),
      {
        name: 'format',
        type: 'string',
        desc: 'jpeg, webp, avif, png (default: keep jpeg/png/webp)',
        values: ['jpeg', 'webp', 'avif', 'png'],
      },
      n('quality', '1-100 (defaults: jpeg 82, webp 80, avif 50)'),
      b('sharpen', 'light unsharp after a downscale'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop (cover only)',
        values: ['attention', 'entropy'],
      },
      s('out-dir', 'output folder (default renders/images)'),
      n('concurrency', 'parallel images (default min(cores-1, 4))'),
      b('no-resume', 'reprocess everything'),
    ],
  }),
  cmd({
    name: 'image.convert',
    module: 'image',
    fn: 'convert',
    writes: true,
    summary: 'Convert image formats without resizing.',
    usage: 'studio image convert <files|folders...> --format webp',
    example: 'studio image convert logo.png --format webp --quality 90',
    flags: [
      n('width', 'target width px'),
      n('height', 'target height px'),
      {
        name: 'mode',
        type: 'string',
        desc: 'inside (default), cover, contain, fill',
        values: ['inside', 'cover', 'contain', 'fill'],
      },
      s('background', 'colour for contain and for flattening alpha, #rrggbb'),
      b('allow-enlarge', 'allow output larger than the source'),
      {
        name: 'format',
        type: 'string',
        desc: 'jpeg, webp, avif, png (default: keep jpeg/png/webp)',
        values: ['jpeg', 'webp', 'avif', 'png'],
      },
      n('quality', '1-100 (defaults: jpeg 82, webp 80, avif 50)'),
      b('sharpen', 'light unsharp after a downscale'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop (cover only)',
        values: ['attention', 'entropy'],
      },
      s('out-dir', 'output folder (default renders/images)'),
      n('concurrency', 'parallel images (default min(cores-1, 4))'),
      b('no-resume', 'reprocess everything'),
    ],
  }),
  cmd({
    name: 'image.bgremove',
    module: 'image',
    fn: 'bgremove',
    writes: true,
    summary:
      'Cut out the subject (U2-Net via onnxruntime). Writes a PNG with alpha and a light/dark check image to look at. Records model and license.',
    usage: 'studio image bgremove <file> [--model u2net|u2netp] [--mask-in FILE]',
    example: 'studio image bgremove portrait.jpg',
    flags: [
      s('model', 'u2net (default) or u2netp (smaller, rougher)'),
      s('mask-in', 'use this grayscale mask instead of the model (same size as the image)'),
      s('out', 'output base name'),
      { name: 'format', type: 'string', desc: 'png (default) or webp', values: ['png', 'webp'] },
      b('no-preview', 'skip the light/dark check image'),
    ],
  }),
  cmd({
    name: 'image.upscale',
    module: 'image',
    fn: 'upscale',
    writes: true,
    summary:
      'Upscale once with Real-ESRGAN (invents detail). --estimate times a small crop first. Needs a Vulkan device; a software one is slow.',
    usage: 'studio image upscale <file> [--scale 2|3|4] [--width N] [--estimate]',
    example: 'studio image upscale small.png --scale 4 --estimate',
    flags: [
      n('scale', '2, 3, or 4 (default 4)'),
      {
        name: 'model',
        type: 'string',
        desc: 'realesrgan-x4plus (photos, default), realesrgan-x4plus-anime, realesr-animevideov3',
        values: ['realesrgan-x4plus', 'realesrgan-x4plus-anime', 'realesr-animevideov3'],
      },
      n('tile', 'tile size px (default 256, lowered automatically on failure)'),
      n('width', 'resize once to this width after upscaling'),
      b('estimate', 'predict the run time from two small crops, write nothing'),
      s('out', 'output base name'),
    ],
  }),
  cmd({
    name: 'image.grade',
    module: 'image',
    fn: 'grade',
    writes: true,
    summary:
      'Colour grade: exposure, white balance, contrast, highlights/shadows, saturation, vibrance, LUT, sharpen, grain (in that order). Reports luma and clipping before and after.',
    usage:
      'studio image grade <files...> [--exposure 0.5 --contrast 10 ...] [--lut F --lut-space srgb] [--match REF] [--before-after]',
    example: 'studio image grade shot.jpg --exposure 0.4 --shadows 20 --before-after',
    flags: [
      n('exposure', 'stops, -5 to 5'),
      n('temperature', '-100 cool to 100 warm'),
      n('tint', '-100 green to 100 magenta'),
      n('contrast', '-100 to 100'),
      n('highlights', '-100 to 100'),
      n('shadows', '-100 to 100'),
      n('saturation', '-100 to 100'),
      n('vibrance', '-100 to 100'),
      s('lut', '.cube 3D LUT'),
      s('lut-space', 'colour space the LUT expects: srgb or rec709 (log LUTs are refused)'),
      n('sharpen', '0 to 3'),
      n('grain', '0 to 40 (seeded)'),
      s('match', 'reference image: match channel means to it'),
      { name: 'format', type: 'string', desc: 'png, jpeg, webp', values: ['png', 'jpeg', 'webp'] },
      n('quality', '1-100'),
      s('out-dir', 'output folder (default renders/images/graded)'),
      b('before-after', 'write a side-by-side image'),
    ],
  }),
  cmd({
    name: 'image.thumbnail',
    module: 'image',
    fn: 'thumbnail',
    writes: true,
    summary:
      'One thumbnail: background frame/photo, optional cutout subject, headline (5 words max) with a contrast-checked scrim. Writes a 168 px legibility copy and the reasons for the layout.',
    usage:
      'studio image thumbnail (--image F | --from-video V --at MS) --headline "TEXT" [--subject cutout.png] [--font F]',
    example:
      'studio image thumbnail --from-video renders/demo-v1.mp4 --at 4200 --headline "Ship it faster" --subject renders/images/me-cutout.png',
    flags: [
      s('image', 'background image'),
      s('from-video', 'take the background from this video'),
      n('at', 'frame time in ms for --from-video'),
      s('headline', 'at most 5 words', true),
      s('subject', 'cutout PNG with alpha'),
      s('font', 'font file (default: first in brand/fonts)'),
      s('palette', 'palette JSON (default brand/palette.json)'),
      {
        name: 'text-side',
        type: 'string',
        desc: 'left (default) or right',
        values: ['left', 'right'],
      },
      b('vertical', '1080x1920 instead of 1280x720'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop of the background',
        values: ['attention', 'entropy'],
      },
      { name: 'format', type: 'string', desc: 'jpeg (default) or png', values: ['jpeg', 'png'] },
      s('out', 'output base name'),
    ],
  }),
  cmd({
    name: 'transcribe',
    module: 'captions',
    fn: 'transcribe',
    writes: true,
    summary:
      'Transcribe speech with word timestamps (faster-whisper, VAD first). Raw output is cached read-only; an editable derived transcript is written.',
    usage:
      'studio transcribe <asset|file> [--model whisper-small] [--language en] [--out transcripts/x.json]',
    example: 'studio transcribe a_1k3f --model whisper-small',
    flags: [
      s('model', 'whisper-tiny.en | whisper-small (default) | whisper-medium'),
      s('language', 'language code; detected when omitted'),
      s('out', 'derived transcript path'),
    ],
  }),
  cmd({
    name: 'captions.build',
    module: 'captions',
    fn: 'build',
    writes: true,
    summary:
      'Build caption cues from a transcript (2 lines, 42 chars, 17 cps, 1-7 s, gaps) and check them by script.',
    usage:
      'studio captions build --transcript T [--clip c_xx] [--style clean|social|karaoke] [--clean]',
    example:
      'studio captions build --transcript transcripts/a_1k3f.whisper-small.json --style karaoke',
    flags: [
      s('transcript', 'derived transcript', true),
      s('clip', 'media clip that places the transcript on the timeline'),
      s('style', 'clean | social | karaoke'),
      s('position', 'bottom | center | top'),
      n('size-pct', 'font size as % of frame height'),
      n('words-per-cue', 'social style: words per cue (relaxes cps and min duration)'),
      n('max-chars', 'characters per line'),
      n('max-cps', 'characters per second'),
      b('clean', 'remove fillers (um, uh): clean-verbatim'),
      n('fps', 'frame rate for timing'),
      n('width', 'canvas width for the safe-zone check'),
      n('height', 'canvas height'),
      s('out', 'cue file'),
    ],
  }),
  cmd({
    name: 'captions.check',
    module: 'captions',
    fn: 'check',
    writes: false,
    summary:
      'Check a cue file against the caption limits and the safe zone (layout measured in Chromium). Exit 4 on violations.',
    usage: 'studio captions check --cues FILE [--width W --height H]',
    example: 'studio captions check --cues captions/x.clean.cues.json',
    flags: [s('cues', 'cue file', true), n('width', 'canvas width'), n('height', 'canvas height')],
  }),
  cmd({
    name: 'captions.export',
    module: 'captions',
    fn: 'exportCmd',
    writes: true,
    summary: 'Write a sidecar caption file: SRT, WebVTT, or styled ASS.',
    usage: 'studio captions export --cues FILE --format srt|vtt|ass [--out FILE]',
    example: 'studio captions export --cues captions/x.clean.cues.json --format srt',
    flags: [
      s('cues', 'cue file', true),
      s('format', 'srt (default) | vtt | ass'),
      s('out', 'output file'),
      n('width', 'ASS canvas width'),
      n('height', 'ASS canvas height'),
    ],
  }),
  cmd({
    name: 'captions.add',
    module: 'captions',
    fn: 'add',
    writes: true,
    summary:
      'Put the cues on the timeline as a burned-in caption clip (an op: validated, logged, undoable).',
    usage: 'studio captions add --cues FILE [--track t_xx]',
    example: 'studio captions add --cues captions/x.clean.cues.json',
    flags: [s('cues', 'cue file', true), s('track', 'captions track (created when omitted)')],
  }),
  cmd({
    name: 'mcp',
    module: 'mcp',
    writes: false,
    summary:
      'Run an MCP server on stdio: every command except ui and mcp is a tool, executed by the same CLI.',
    usage: 'studio mcp [--project DIR]',
    example:
      'claude mcp add studio -- node packages/cli/dist/studio.js mcp --project /path/to/project',
    flags: [],
  }),
  cmd({
    name: 'plugins.list',
    module: 'plugins',
    fn: 'list',
    writes: false,
    summary: 'List loaded plugins (shipped and in the project) with their templates, effects, scripts, and sizes.',
    usage: 'studio plugins list [--id ID]',
    example: 'studio plugins list',
    flags: [s('id', 'show one plugin')],
  }),
  cmd({
    name: 'plugins.new',
    module: 'plugins',
    fn: 'newPlugin',
    writes: true,
    summary: 'Scaffold a plugin in the project: a motion template, a video effect, or a script.',
    usage: 'studio plugins new <id> [--kind template|effect|script]',
    example: 'studio plugins new my-glow --kind effect',
    flags: [s('kind', 'template (default), effect, or script')],
  }),
  cmd({
    name: 'plugins.check',
    module: 'plugins',
    fn: 'check',
    writes: true,
    summary: 'Validate a plugin and exercise it: effects run on a test pattern, templates render a frame.',
    usage: 'studio plugins check <id>',
    example: 'studio plugins check my-glow',
    flags: [],
  }),
  cmd({
    name: 'plugins.apply',
    module: 'plugins',
    fn: 'apply',
    writes: true,
    summary: 'Add a plugin video effect to a clip (an op: validated, logged, undoable).',
    usage: 'studio plugins apply --clip c_xx --effect ID [--params JSON]',
    example: 'studio plugins apply --clip c_01 --effect glow --params \'{"amount":0.6}\'',
    flags: [s('clip', 'clip id', true), s('effect', 'plugin effect id', true), s('params', 'parameters as JSON')],
  }),
  cmd({
    name: 'expr.eval',
    module: 'expr',
    fn: 'evaluate',
    writes: false,
    summary: 'Evaluate an animation formula at times, to check it before baking it into keyframes.',
    usage: 'studio expr eval --expr "1 + 0.2 * sin(t * 6)" [--at 0,0.5,1] [--dur S]',
    example: 'studio expr eval --expr "1 + 0.2 * expo_out(p)" --at 0,0.5,1',
    flags: [s('expr', 'formula', true), s('at', 'seconds, comma separated'), n('dur', 'clip length in seconds (for p)'), s('vars', 'extra variables as JSON')],
  }),
  cmd({
    name: 'expr.bake',
    module: 'expr',
    fn: 'bake',
    writes: true,
    summary: 'Sample a formula over part of a clip and write it as keyframes (one undoable step).',
    usage: 'studio expr bake --clip c_xx --prop scale --expr "1 + 0.1 * wiggle(2, 1)" [--from MS --to MS --step MS --ease linear]',
    example: 'studio expr bake --clip c_01 --prop scale --expr "1 + 0.3 * expo_out(p)" --from 0 --to 1500',
    flags: [s('clip', 'clip id', true), s('prop', 'scale, x, or y', true), s('expr', 'formula', true), n('from', 'start, ms into the clip'), n('to', 'end, ms into the clip'), n('step', 'sample spacing in ms (min 40)'), s('ease', 'easing between samples')],
  }),
  cmd({
    name: 'script.list',
    module: 'script',
    fn: 'list',
    writes: false,
    summary: 'List scripts: the shipped library, the project scripts folder, and plugin scripts.',
    usage: 'studio script list',
    example: 'studio script list',
    flags: [],
  }),
  cmd({
    name: 'script.run',
    module: 'script',
    fn: 'run',
    writes: true,
    summary: 'Run a script. It changes the project only through studio commands, so every change is an op.',
    usage: 'studio script run <name> [--args JSON]',
    example: 'studio script run zoom-punch --args \'{"clip":"c_01","at":2000}\'',
    flags: [s('args', 'script arguments as JSON')],
  }),
  cmd({
    name: 'color.effects',
    module: 'color',
    fn: 'effects',
    writes: false,
    summary: 'List every colour and look effect (and other plugin effects) with parameter ranges and cost.',
    usage: 'studio color effects [--query WORD]',
    example: 'studio color effects --query curves',
    flags: [s('query', 'filter by word in the id or summary')],
  }),
  cmd({
    name: 'color.stack',
    module: 'color',
    fn: 'stack',
    writes: false,
    summary: "Show a clip's node stack: each node's index, effect, parameters (defaults filled in), and bypass state.",
    usage: 'studio color stack --clip c_xx',
    example: 'studio color stack --clip c_01',
    flags: [s('clip', 'media clip id', true)],
  }),
  cmd({
    name: 'color.add',
    module: 'color',
    fn: 'add',
    writes: true,
    summary: 'Add a colour or look node to a clip (validated, logged, undoable).',
    usage: 'studio color add --clip c_xx --effect ID [--params JSON] [--at INDEX]',
    example: 'studio color add --clip c_01 --effect lumetri --params \'{"exposure":0.5}\'',
    flags: [s('clip', 'media clip id', true), s('effect', 'effect id', true), s('params', 'parameters as JSON'), n('at', 'insert position in the stack (default: end)')],
  }),
  cmd({
    name: 'color.set',
    module: 'color',
    fn: 'set',
    writes: true,
    summary: "Change a node's parameters (merged with its current ones; --replace resets the rest to defaults).",
    usage: 'studio color set --clip c_xx --node N --params JSON [--replace]',
    example: 'studio color set --clip c_01 --node 0 --params \'{"contrast":15}\'',
    flags: [s('clip', 'media clip id', true), n('node', 'node index from studio color stack', true), s('params', 'parameters as JSON', true), b('replace', 'start from defaults instead of merging')],
  }),
  cmd({
    name: 'color.remove',
    module: 'color',
    fn: 'remove',
    writes: true,
    summary: "Remove a node from a clip's stack.",
    usage: 'studio color remove --clip c_xx --node N',
    example: 'studio color remove --clip c_01 --node 1',
    flags: [s('clip', 'media clip id', true), n('node', 'node index', true)],
  }),
  cmd({
    name: 'color.move',
    module: 'color',
    fn: 'move',
    writes: true,
    summary: 'Move a node to another position in the stack.',
    usage: 'studio color move --clip c_xx --node N --to M',
    example: 'studio color move --clip c_01 --node 2 --to 0',
    flags: [s('clip', 'media clip id', true), n('node', 'node index', true), n('to', 'new index', true)],
  }),
  cmd({
    name: 'color.bypass',
    module: 'color',
    fn: 'bypass',
    writes: true,
    summary: 'Switch a node off (kept in the stack, skipped by the render); --off switches it back on.',
    usage: 'studio color bypass --clip c_xx --node N [--off]',
    example: 'studio color bypass --clip c_01 --node 0',
    flags: [s('clip', 'media clip id', true), n('node', 'node index', true), b('off', 'enable the node again')],
  }),
  cmd({
    name: 'color.lut',
    module: 'color',
    fn: 'lut',
    writes: true,
    summary: 'Add a 3D LUT (.cube or .3dl, inside the project) to a clip.',
    usage: 'studio color lut --clip c_xx --file luts/look.cube',
    example: 'studio color lut --clip c_01 --file luts/film.cube',
    flags: [s('clip', 'media clip id', true), s('file', 'LUT path inside the project', true)],
  }),
  cmd({
    name: 'color.analyze',
    module: 'color',
    fn: 'analyze',
    writes: false,
    summary: 'Measure a frame: luma percentiles, clipping, per-channel mean and spread, midtone cast, saturation, with plain notes.',
    usage: 'studio color analyze (--clip c_xx [--at MS] | --file F [--at MS])',
    example: 'studio color analyze --clip c_01',
    flags: [s('clip', 'media clip id (measures the rendered timeline frame)'), s('file', 'an image or video file instead'), n('at', 'time in ms (timeline for --clip, file time for --file)')],
  }),
  cmd({
    name: 'color.scopes',
    module: 'color',
    fn: 'scopes',
    writes: true,
    summary: 'Write waveform, RGB parade, vectorscope and histogram images and a combined sheet for a frame.',
    usage: 'studio color scopes (--clip c_xx [--at MS] | --file F [--at MS])',
    example: 'studio color scopes --clip c_01',
    flags: [s('clip', 'media clip id'), s('file', 'an image or video file instead'), n('at', 'time in ms')],
  }),
  cmd({
    name: 'color.auto',
    module: 'color',
    fn: 'auto',
    writes: true,
    summary: 'Measure a frame and add a lumetri node that corrects exposure, contrast, black and white points, white balance (reports before and after).',
    usage: 'studio color auto --clip c_xx [--at MS] [--report-only]',
    example: 'studio color auto --clip c_01',
    flags: [s('clip', 'media clip id', true), n('at', 'timeline ms to measure'), b('report-only', 'suggest, change nothing')],
  }),
  cmd({
    name: 'color.match',
    module: 'color',
    fn: 'match',
    writes: true,
    summary: 'Match a shot to a reference clip or image: per-channel gain and offset as a primary node (reports distance before and after).',
    usage: 'studio color match --clip c_xx --ref c_yy|FILE [--strength 0..1]',
    example: 'studio color match --clip c_02 --ref c_01',
    flags: [s('clip', 'media clip id', true), s('ref', 'reference clip id or file', true), n('at', 'timeline ms to measure the target'), n('ref-at', 'ms to measure the reference'), n('strength', '0 to 1, default 1')],
  }),
  cmd({
    name: 'color.save',
    module: 'color',
    fn: 'save',
    writes: true,
    summary: "Save a clip's colour nodes as a named grade in the project's gallery (grades/NAME.json).",
    usage: 'studio color save --clip c_xx --name NAME',
    example: 'studio color save --clip c_01 --name warm-day',
    flags: [s('clip', 'media clip id', true), s('name', 'grade name: lowercase, digits, dashes', true)],
  }),
  cmd({
    name: 'color.gallery',
    module: 'color',
    fn: 'gallery',
    writes: false,
    summary: 'List saved grades.',
    usage: 'studio color gallery',
    example: 'studio color gallery',
    flags: [],
  }),
  cmd({
    name: 'color.apply',
    module: 'color',
    fn: 'apply',
    writes: true,
    summary: 'Apply a saved grade to clips (appended; --replace swaps their existing colour nodes).',
    usage: 'studio color apply --name NAME --clips c_a,c_b [--replace]',
    example: 'studio color apply --name warm-day --clips c_02,c_03',
    flags: [s('name', 'saved grade', true), s('clips', 'comma separated clip ids', true), b('replace', 'remove the clips existing colour nodes first')],
  }),
  cmd({
    name: 'color.still',
    module: 'color',
    fn: 'still',
    writes: true,
    summary: 'Run a list of nodes on an image file and write a PNG (images get the same tools as video).',
    usage: 'studio color still --file F --nodes JSON [--out PATH]',
    example: 'studio color still --file photo.jpg --nodes \'[{"id":"lumetri","params":{"exposure":0.5}}]\'',
    flags: [s('file', 'image file', true), s('nodes', 'JSON array of {id, params}', true), s('out', 'output PNG path')],
  }),
  cmd({
    name: 'design.new',
    module: 'design',
    fn: 'create',
    writes: true,
    summary: 'Create a design project (its own design.studio.json) in the project folder: a scene with a size, frame rate, and length.',
    usage: 'studio design new <name> [--width N --height N --fps N --duration MS --background #rrggbb|transparent]',
    example: 'studio design new "Launch teaser" --width 1080 --height 1920 --fps 30 --duration 6000',
    flags: [n('width','scene width px'), n('height','scene height px'), n('fps','frame rate'), n('duration','scene length in ms'), s('background','#RRGGBB or transparent')],
  }),
  cmd({
    name: 'design.show',
    module: 'design',
    fn: 'show',
    writes: false,
    summary: 'Summarize the design: scene, the layer tree with ids, which layers are animated, and undo depth.',
    usage: 'studio design show [--full]',
    example: 'studio design show',
    flags: [b('full','include the whole design document')],
  }),
  cmd({
    name: 'design.scene',
    module: 'design',
    fn: 'scene',
    writes: true,
    summary: 'Change the scene: name, size, frame rate, length, background.',
    usage: 'studio design scene [--name N --width N --height N --fps N --duration MS --background C]',
    example: 'studio design scene --duration 8000',
    flags: [s('name','scene name'), n('width','px'), n('height','px'), n('fps','frame rate'), n('duration','ms'), s('background','#RRGGBB or transparent')],
  }),
  cmd({
    name: 'design.add',
    module: 'design',
    fn: 'add',
    writes: true,
    summary: 'Add a layer: frame, group, rect, ellipse, star, path, text, image, audio. Defaults are filled in; --props overrides any property.',
    usage: 'studio design add <type> [--name N --parent ID --index N --text T --src assets/F --props JSON]',
    example: 'studio design add text --text "Hello" --props \'{"x":120,"y":300,"fontSize":96}\'',
    flags: [s('name','layer name'), s('parent','parent frame or group id'), n('index','position among siblings, 0 = back'), s('text','text content'), s('src','asset path for image or audio'), s('props','any layer properties as JSON')],
  }),
  cmd({
    name: 'design.set',
    module: 'design',
    fn: 'set',
    writes: true,
    summary: 'Change layer properties (JSON patch; null removes an optional property). Several ids at once.',
    usage: 'studio design set --id ID[,ID] --props JSON',
    example: 'studio design set --id l_k3f9 --props \'{"x":200,"opacity":0.8,"fill":{"type":"solid","color":"#ff3366"}}\'',
    flags: [s('id', 'layer id (comma separated for several)', true), s('props','property patch as JSON', true)],
  }),
  cmd({
    name: 'design.move',
    module: 'design',
    fn: 'move',
    writes: true,
    summary: 'Move a layer to another parent and/or position among siblings (0 = back).',
    usage: 'studio design move --id ID [--parent ID|scene] [--index N]',
    example: 'studio design move --id l_k3f9 --index 0',
    flags: [s('id', 'layer id (comma separated for several)', true), s('parent','new parent id, or scene'), n('index','position among siblings')],
  }),
  cmd({
    name: 'design.delete',
    module: 'design',
    fn: 'remove',
    writes: true,
    summary: 'Delete layers and everything inside them (undoable).',
    usage: 'studio design delete --id ID[,ID]',
    example: 'studio design delete --id l_k3f9',
    flags: [s('id', 'layer id (comma separated for several)', true)],
  }),
  cmd({
    name: 'design.duplicate',
    module: 'design',
    fn: 'duplicate',
    writes: true,
    summary: 'Duplicate a layer with its children and keyframes.',
    usage: 'studio design duplicate --id ID [--dx N --dy N]',
    example: 'studio design duplicate --id l_k3f9 --dx 40',
    flags: [s('id', 'layer id (comma separated for several)', true), n('dx','x offset of the copy'), n('dy','y offset of the copy')],
  }),
  cmd({
    name: 'design.group',
    module: 'design',
    fn: 'group',
    writes: true,
    summary: 'Group layers that share a parent; the group takes their bounding box.',
    usage: 'studio design group --ids ID,ID [--name N]',
    example: 'studio design group --ids l_aaaa,l_bbbb --name Card',
    flags: [s('ids','layer ids, comma separated', true), s('name','group name')],
  }),
  cmd({
    name: 'design.ungroup',
    module: 'design',
    fn: 'ungroup',
    writes: true,
    summary: 'Dissolve a group or frame, keeping its children where they are.',
    usage: 'studio design ungroup --id ID',
    example: 'studio design ungroup --id l_k3f9',
    flags: [s('id', 'layer id (comma separated for several)', true)],
  }),
  cmd({
    name: 'design.align',
    module: 'design',
    fn: 'align',
    writes: true,
    summary: 'Align layers to the scene (one layer) or to each other (several): left, center, right, top, middle, bottom.',
    usage: 'studio design align --ids ID,ID --to left|center|right|top|middle|bottom [--relative scene|selection]',
    example: 'studio design align --ids l_aaaa --to center',
    flags: [s('ids','layer ids', true), s('to','edge or centre', true), s('relative','scene or selection')],
  }),
  cmd({
    name: 'design.keyframe',
    module: 'design',
    fn: 'keyframe',
    writes: true,
    summary: 'Set or delete a keyframe: a value of a property at a time, with an easing to the next keyframe.',
    usage: 'studio design keyframe --layer ID --prop P --t MS (--v N | --color #rrggbb) [--ease NAME] | --layer ID --delete k_xxxx',
    example: 'studio design keyframe --layer l_k3f9 --prop x --t 0 --v -300 --ease expo.out',
    flags: [s('layer','layer id', true), s('prop','x y w h rotation opacity scale cornerRadius strokeWidth shadowX shadowY shadowBlur layerBlur trim charProgress volume fill stroke'), n('t','time in ms'), n('v','number value'), s('color','colour value for fill or stroke'), s('ease','easing: linear, hold, quad|cubic|expo|back|elastic|bounce|spring .in|.out|.inOut, bezier(...)'), s('delete','keyframe id to delete')],
  }),
  cmd({
    name: 'design.clear',
    module: 'design',
    fn: 'clear',
    writes: true,
    summary: 'Remove the keyframes of a property (or of the whole layer).',
    usage: 'studio design clear --layer ID [--prop P]',
    example: 'studio design clear --layer l_k3f9 --prop x',
    flags: [s('layer','layer id', true), s('prop','property; default all')],
  }),
  cmd({
    name: 'design.animate',
    module: 'design',
    fn: 'animate',
    writes: true,
    summary: 'Apply an animation preset (the Animate tab): fade-in, slide-in, pop, bounce, typewriter, draw-on, ... Several layers at once.',
    usage: 'studio design animate --layer ID[,ID] --preset NAME [--at MS --dur MS --ease E --from left|right|top|bottom --distance PX --amount N --count N --to #rrggbb]',
    example: 'studio design animate --layer l_k3f9 --preset slide-in --from bottom --at 200',
    flags: [s('layer','layer id(s)', true), s('preset','preset id (studio design presets)', true), n('at','start ms'), n('dur','length ms'), s('ease','easing'), s('from','edge'), n('distance','px'), n('amount','strength'), n('count','repeats'), s('to','target colour')],
  }),
  cmd({
    name: 'design.presets',
    module: 'design',
    fn: 'presets',
    writes: false,
    summary: 'List animation presets and the animatable properties.',
    usage: 'studio design presets',
    example: 'studio design presets',
    flags: [],
  }),
  cmd({
    name: 'design.apply',
    module: 'design',
    fn: 'applyOps',
    writes: true,
    summary: 'Apply a JSON array of ops atomically (all or none). The most direct way to build a design.',
    usage: 'studio design apply <ops.json|->',
    example: 'studio design apply ops.json',
    flags: [],
  }),
  cmd({
    name: 'design.undo',
    module: 'design',
    fn: 'undo',
    writes: true,
    summary: 'Undo the last transaction(s).',
    usage: 'studio design undo [--n N]',
    example: 'studio design undo',
    flags: [n('n','how many')],
  }),
  cmd({
    name: 'design.redo',
    module: 'design',
    fn: 'redo',
    writes: true,
    summary: 'Redo undone transaction(s).',
    usage: 'studio design redo [--n N]',
    example: 'studio design redo',
    flags: [n('n','how many')],
  }),
  cmd({
    name: 'design.log',
    module: 'design',
    fn: 'log',
    writes: false,
    summary: 'List recent design operations (who did what).',
    usage: 'studio design log [--limit N]',
    example: 'studio design log',
    flags: [n('limit','how many')],
  }),
  cmd({
    name: 'design.asset',
    module: 'design',
    fn: 'assetAdd',
    writes: true,
    summary: "Copy image or audio files into the design's assets folder and print their paths.",
    usage: 'studio design asset <file...>',
    example: 'studio design asset logo.png voiceover.mp3',
    flags: [],
  }),
  cmd({
    name: 'design.validate',
    module: 'design',
    fn: 'validate',
    writes: false,
    summary: 'Check the design file against the schema and invariants.',
    usage: 'studio design validate',
    example: 'studio design validate',
    flags: [],
  }),
  cmd({
    name: 'design.render',
    module: 'design',
    fn: 'render',
    writes: true,
    summary: 'Export: mp4, webm (alpha), mov (ProRes 4444 alpha), gif, a png sequence, or one png. Reports frames, time and speed.',
    usage: 'studio design render [--format F --out PATH --range A:B --at MS --scale N --alpha --force]',
    example: 'studio design render --format mp4',
    flags: [s('format','mp4 (default), webm, mov, gif, png-seq, png'), s('out','output path under the project'), s('range','A:B in ms'), n('at','ms for png'), n('scale','pixel scale 0.25 to 4'), b('alpha','transparent background (webm, mov, png, png-seq, gif)'), n('concurrency','parallel Chromium pages')],
  }),
  cmd({
    name: 'design.still',
    module: 'design',
    fn: 'still',
    writes: true,
    summary: 'Export one frame as a PNG.',
    usage: 'studio design still --at MS [--alpha] [--scale N]',
    example: 'studio design still --at 1500',
    flags: [n('at','time in ms'), b('alpha','transparent background'), n('scale','pixel scale'), s('out','output path')],
  }),
  cmd({
    name: 'design.ui',
    module: 'design',
    fn: 'ui',
    writes: true,
    summary: 'Serve the design and animation editor on localhost; its edits are ops (actor ui) through the same store the CLI uses. Stop with Ctrl+C.',
    usage: 'studio design ui [--port N] [--read-only] [--hub [--root DIR]]',
    example: 'studio design ui --hub --root ~/edits',
    flags: [
      n('port', 'port (default 4174, 0 = any free port)'),
      b('read-only', 'refuse edits from the page'),
      b('hub', 'serve the design workspaces d1..d5 under <root>/workspaces, with a tab for each, instead of one design'),
      s('root', 'folder that holds workspaces/ (default: $STUDIO_ROOT or the project folder)'),
    ],
  }),
  cmd({
    name: 'motion.templates',
    module: 'motion',
    fn: 'templates',
    writes: false,
    summary: 'List motion templates and the props each accepts (type, default, limits).',
    usage: 'studio motion templates [--comp NAME]',
    example: 'studio motion templates --comp lower-third',
    flags: [s('comp', 'show one template')],
  }),
  cmd({
    name: 'motion.scaffold',
    module: 'motion',
    fn: 'scaffold',
    writes: true,
    summary: 'Write a starting props file for a template (edit the JSON, not code).',
    usage: 'studio motion scaffold --comp NAME [--out motion/props/NAME.json]',
    example: 'studio motion scaffold --comp lower-third',
    flags: [s('comp', 'template id', true), s('out', 'props file to write')],
  }),
  cmd({
    name: 'motion.still',
    module: 'motion',
    fn: 'still',
    writes: true,
    summary:
      'Render one frame of a template or project composition clip to PNG (check before rendering video).',
    usage:
      'studio motion still (--comp NAME [--props FILE|JSON] | --clip c_xx) [--frame N | --at MS] [--checker]',
    example:
      'studio motion still --comp lower-third --props motion/props/lower-third.json --at 1500 --checker',
    flags: [
      s('comp', 'template id'),
      s('clip', 'project composition clip'),
      s('props', 'props file or JSON'),
      n('frame', 'frame number'),
      n('at', 'time in ms'),
      n('dur', 'duration ms (default: template)'),
      n('width', 'canvas width'),
      n('height', 'canvas height'),
      n('fps', 'frames per second'),
      s('out', 'output PNG'),
      b('checker', 'paint a checkerboard behind, to inspect alpha'),
    ],
  }),
  cmd({
    name: 'motion.render',
    module: 'motion',
    fn: 'render',
    writes: true,
    summary:
      'Render a template or composition clip to an alpha overlay: ProRes 4444, VP9 WebM, or PNG sequence. Cached by hash.',
    usage:
      'studio motion render (--comp NAME [--props FILE|JSON] | --clip c_xx) [--format prores4444|webm|png] [--out FILE]',
    example:
      'studio motion render --comp lower-third --props motion/props/lower-third.json --dur 4000',
    flags: [
      s('comp', 'template id'),
      s('clip', 'project composition clip'),
      s('props', 'props file or JSON'),
      n('dur', 'duration ms'),
      n('width', 'canvas width'),
      n('height', 'canvas height'),
      n('fps', 'frames per second'),
      s('format', 'prores4444 (default) | webm | png'),
      s('out', 'output file'),
      n('concurrency', 'browser pages (default: half the cores)'),
    ],
  }),
  cmd({
    name: 'models.list',
    module: 'models',
    fn: 'list',
    writes: false,
    summary: 'List models and engine binaries: installed or not, license, source.',
    usage: 'studio models list',
    example: 'studio models list',
    flags: [],
  }),
  cmd({
    name: 'models.fetch',
    module: 'models',
    fn: 'fetch',
    writes: true,
    summary: 'Download a model or engine, checking size and sha256 against models/manifest.json.',
    usage: 'studio models fetch <name...> | --all [--force]',
    example: 'studio models fetch u2net',
    flags: [b('all', 'every model in the manifest')],
  }),
  cmd({
    name: 'project.set',
    module: 'project',
    writes: true,
    summary:
      'Change the project name, canvas size, frame rate, or background (an op: validated, logged, undoable).',
    usage:
      'studio project set [--name N] [--width W] [--height H] [--fps F] [--background #RRGGBB]',
    example: 'studio project set --width 1080 --height 1920 --fps 30',
    flags: [
      s('name', 'project name'),
      n('width', 'canvas width in px'),
      n('height', 'canvas height in px'),
      n('fps', 'frames per second'),
      s('background', 'background color #RRGGBB'),
    ],
  }),
  cmd({
    name: 'project.show',
    module: 'project',
    writes: false,
    summary: 'Summarize the project (tracks, clips, assets, derived duration, undo depth).',
    usage: 'studio project show [--full]',
    example: 'studio project show',
    flags: [b('full', 'include the whole project file')],
  }),
  cmd({
    name: 'project.validate',
    module: 'project',
    writes: false,
    summary: 'Check schema and invariants; warns if the file was edited outside ops.',
    usage: 'studio project validate',
    example: 'studio project validate',
    flags: [],
  }),
  cmd({
    name: 'project.diff',
    module: 'project',
    writes: false,
    summary: 'Show the ops of one transaction (by txn or op id).',
    usage: 'studio project diff <txnId|opId>',
    example: 'studio project diff tx_ab12cd',
    flags: [],
  }),
  cmd({
    name: 'project.log',
    module: 'project',
    writes: false,
    summary: 'List recent log entries.',
    usage: 'studio project log [--limit N]',
    example: 'studio project log --limit 10',
    flags: [n('limit', 'entries to show (default 20)')],
  }),
  cmd({
    name: 'project.undo',
    module: 'project',
    writes: true,
    summary: 'Undo the last transaction(s) by applying inverse ops; logs the undo.',
    usage: 'studio project undo [--n N]',
    example: 'studio project undo --n 2',
    flags: [n('n', 'transactions to undo (default 1)')],
  }),
  cmd({
    name: 'project.redo',
    module: 'project',
    writes: true,
    summary: 'Redo undone transaction(s).',
    usage: 'studio project redo [--n N]',
    example: 'studio project redo',
    flags: [n('n', 'transactions to redo (default 1)')],
  }),
  cmd({
    name: 'ops.apply',
    module: 'ops',
    writes: true,
    summary: 'Apply a JSON batch of ops atomically (all or none). File path or - for stdin.',
    usage: 'studio ops apply <ops.json|->',
    example: 'studio ops apply ops.json --dry-run',
    flags: [s('label', 'log label')],
  }),
  cmd({
    name: 'tl.add-track',
    module: 'tl',
    writes: true,
    summary: 'Add a track.',
    usage: 'studio tl add-track --type video|audio|graphics|captions --name N',
    example: 'studio tl add-track --type video --name Screen',
    flags: [
      {
        name: 'type',
        type: 'string',
        desc: 'track type',
        required: true,
        values: ['video', 'audio', 'graphics', 'captions'],
      },
      s('name', 'track name', true),
      s('role', 'e.g. music'),
      s('id', 'explicit id'),
      n('index', 'position'),
    ],
  }),
  cmd({
    name: 'tl.add-clip',
    module: 'tl',
    writes: true,
    summary: 'Add a clip from an asset or a composition.',
    usage: 'studio tl add-clip --track t --asset a|--comp name --start MS --dur MS',
    example: 'studio tl add-clip --track t_v1 --asset a_k3f9 --start 0 --dur 8200 --src-in 12000',
    flags: [
      s('track', 'track id', true),
      s('asset', 'asset id'),
      s('comp', 'composition id'),
      n('start', 'timeline ms', true),
      n('dur', 'duration ms', true),
      n('src-in', 'source in-point ms'),
      s('props', 'JSON props for comp clips'),
      s('id', 'explicit id'),
    ],
  }),
  cmd({
    name: 'tl.move',
    module: 'tl',
    writes: true,
    summary: 'Move a clip to an absolute start (optionally another track).',
    usage: 'studio tl move --id c --start MS [--track t]',
    example: 'studio tl move --id c_01 --start 1500',
    flags: [s('id', 'clip id', true), n('start', 'timeline ms', true), s('track', 'target track')],
  }),
  cmd({
    name: 'tl.trim',
    module: 'tl',
    writes: true,
    summary: 'Set absolute start, duration, or source in-point.',
    usage: 'studio tl trim --id c [--start MS] [--dur MS] [--src-in MS]',
    example: 'studio tl trim --id c_01 --dur 4000',
    flags: [
      s('id', 'clip id', true),
      n('start', 'timeline ms'),
      n('dur', 'duration ms'),
      n('src-in', 'source in-point ms'),
    ],
  }),
  cmd({
    name: 'tl.split',
    module: 'tl',
    writes: true,
    summary: 'Split a clip at a timeline time.',
    usage: 'studio tl split --id c --at MS',
    example: 'studio tl split --id c_01 --at 3000',
    flags: [s('id', 'clip id', true), n('at', 'timeline ms', true)],
  }),
  cmd({
    name: 'tl.ripple-delete',
    module: 'tl',
    writes: true,
    summary: 'Delete a clip and close the gap.',
    usage: 'studio tl ripple-delete --id c [--scope track|all]',
    example: 'studio tl ripple-delete --id c_01 --scope all',
    flags: [
      s('id', 'clip id', true),
      { name: 'scope', type: 'string', desc: 'which tracks shift', values: ['track', 'all'] },
    ],
  }),
  cmd({
    name: 'tl.set',
    module: 'tl',
    writes: true,
    summary: 'Patch clip transform, fx, props, link, label (JSON; null removes a field).',
    usage: 'studio tl set --id c --patch JSON',
    example: `studio tl set --id c_01 --patch '{"transform":{"scale":1.2}}'`,
    flags: [s('id', 'clip id', true), s('patch', 'JSON patch', true)],
  }),
  cmd({
    name: 'tl.keyframe',
    module: 'tl',
    writes: true,
    summary: 'Set a keyframe (or delete one with --delete).',
    usage:
      'studio tl keyframe --clip c --prop scale --t MS --v N [--ease expo.inOut] | --clip c --delete k_id',
    example: 'studio tl keyframe --clip c_01 --prop scale --t 1000 --v 1.8 --ease expo.inOut',
    flags: [
      s('clip', 'clip id', true),
      s('prop', 'property name'),
      n('t', 'ms from clip start'),
      n('v', 'value'),
      s('ease', 'easing name'),
      s('delete', 'keyframe id to delete'),
    ],
  }),
  cmd({
    name: 'tl.marker',
    module: 'tl',
    writes: true,
    summary: 'Add a marker.',
    usage: 'studio tl marker --t MS --label TEXT',
    example: 'studio tl marker --t 5000 --label "Click: Save"',
    flags: [n('t', 'timeline ms', true), s('label', 'text', true)],
  }),
  cmd({
    name: 'ws.open',
    module: 'workspace',
    writes: true,
    summary:
      'Open 1 to 5 workspaces at once (at most 5 media and 5 design in use): each is its own project folder, so one agent or subagent per workspace can work in parallel without touching the others. All or nothing.',
    usage:
      'studio ws open [--kind media|design] [--count N] [--name TEXT] [--slot m1] [--root DIR] [--width N --height N --fps N --duration MS --background #rrggbb]',
    example: 'studio ws open --kind media --count 5 --name "Clip"',
    flags: [
      { name: 'kind', type: 'string', desc: 'media (image, video, audio; slots m1..m5) or design (design and animation; slots d1..d5). Default media', values: ['media', 'design'] },
      n('count', 'how many workspaces to open (1 to 5, default 1)'),
      s('name', 'name; with --count the workspaces are "name 1", "name 2", ...'),
      s('slot', 'a specific free slot, e.g. m3 or d2'),
      s('root', 'folder that will hold workspaces/ (default: $STUDIO_ROOT or the project folder)'),
      n('width', 'canvas width'),
      n('height', 'canvas height'),
      n('fps', 'frame rate'),
      n('duration', 'design scene length in ms'),
      s('background', '#RRGGBB (design: or transparent)'),
    ],
  }),
  cmd({
    name: 'ws.list',
    module: 'workspace',
    writes: false,
    summary: 'List the open workspaces with their folder, whether an agent is working in them, and what is in them. Shows how many of the 5 slots per editor are free.',
    usage: 'studio ws list [--kind media|design] [--root DIR]',
    example: 'studio ws list',
    flags: [
      { name: 'kind', type: 'string', desc: 'only this editor', values: ['media', 'design'] },
      s('root', 'folder that holds workspaces/'),
    ],
  }),
  cmd({
    name: 'ws.close',
    module: 'workspace',
    writes: true,
    summary: 'Free a slot: the workspace folder is moved to workspaces/.closed/ (nothing is deleted). Refused while an agent holds it, unless --force.',
    usage: 'studio ws close <slot> [--root DIR] [--force]',
    example: 'studio ws close m2',
    flags: [s('root', 'folder that holds workspaces/')],
  }),
  cmd({
    name: 'work.begin',
    module: 'workspace',
    writes: true,
    summary:
      'Take this workspace for your agent: the editor becomes view-only for the person until you finish. Every write you make with --agent keeps it alive; it expires by itself after --ttl seconds without activity. Another live agent holding it refuses.',
    usage: 'studio work begin --agent NAME [--note TEXT] [--ttl SECONDS]',
    example: 'studio work begin --agent m1-agent --note "cutting the intro" --project workspaces/m1',
    flags: [s('note', 'what you are doing, shown to the person (200 characters)'), n('ttl', 'seconds of inactivity before it expires (1 to 3600, default 120)')],
  }),
  cmd({
    name: 'work.end',
    module: 'workspace',
    writes: true,
    summary: 'Give the workspace back: the editor opens for the person at once. Always do this when you finish.',
    usage: 'studio work end --agent NAME [--force]',
    example: 'studio work end --agent m1-agent --project workspaces/m1',
    flags: [],
  }),
  cmd({
    name: 'work.status',
    module: 'workspace',
    writes: false,
    summary: 'Is an agent working in this workspace, who, and how long until the lease expires.',
    usage: 'studio work status',
    example: 'studio work status --project workspaces/m1',
    flags: [],
  }),
  cmd({
    name: 'fx.list',
    module: 'fx',
    writes: false,
    summary: 'The effect stack of a clip: every effect with its id (node), settings, on/off, which parameters are keyframed. --verify also re-hashes the source file to show it is untouched.',
    usage: 'studio fx list --clip c_xx [--verify]',
    example: 'studio fx list --clip c_01 --verify',
    flags: [s('clip', 'media clip id', true), b('verify', 'hash the original file and compare with the hash recorded at ingest')],
  }),
  cmd({
    name: 'fx.verify',
    module: 'fx',
    writes: false,
    summary: 'Prove the originals are untouched: re-hash the source files and compare with the hashes recorded when they were ingested (all assets, or the one a clip uses).',
    usage: 'studio fx verify [--clip c_xx]',
    example: 'studio fx verify',
    flags: [s('clip', 'only the asset this clip uses')],
  }),
  cmd({
    name: 'fx.add',
    module: 'fx',
    writes: true,
    summary: 'Add an effect on top of a clip (never into the source): a plugin effect, a LUT, or a blur region. Returns its node id for later changes.',
    usage: 'studio fx add --clip c_xx (--effect ID [--params JSON] | --lut FILE | --region x,y,w,h [--strength N] | --gain DB) [--mix 0..1] [--at POSITION] [--bypass]',
    example: 'studio fx add --clip c_01 --effect glow --params \'{"amount":0.6}\'',
    flags: [
      s('clip', 'media clip id', true),
      s('effect', 'plugin effect id (studio color effects lists them)'),
      s('params', 'parameters as JSON'),
      s('lut', 'a .cube or .3dl inside the project'),
      s('region', 'blur region as fractions of the frame: x,y,w,h'),
      n('strength', 'blur strength 2..80'),
      n('gain', 'an audio gain in dB (keyframe its db to fade or duck by hand)'),
      n('mix', 'how much of the effect shows, 0..1 (default 1)'),
      s('matte', 'apply the effect only inside this matte (studio matte add makes one)'),
      b('matte-invert', 'apply it everywhere except inside the matte'),
      n('feather', 'soften the matte edge, px (0..40)'),
      n('choke', 'shrink the matte edge by px (negative grows it)'),
      n('at', 'position in the stack (default: end)'),
      b('bypass', 'add it switched off'),
    ],
  }),
  cmd({
    name: 'fx.set',
    module: 'fx',
    writes: true,
    summary: 'Change an effect: merge parameters (or --replace), switch it on or off, move a blur region. The node is its id (f_xxxx) or its position.',
    usage: 'studio fx set --clip c_xx --node f_xxxx [--params JSON] [--replace] [--mix 0..1] [--bypass | --enable] [--region x,y,w,h] [--strength N]',
    example: 'studio fx set --clip c_01 --node f_k3f9 --params \'{"amount":0.3}\'',
    flags: [
      s('clip', 'media clip id', true),
      s('node', 'effect id or position', true),
      s('params', 'parameters to change, as JSON'),
      b('replace', 'replace all parameters instead of merging'),
      n('mix', 'how much of the effect shows, 0..1 (1 clears it)'),
      s('matte', 'limit the effect (or a cutout) to a matte; `none` lifts the limit'),
      b('matte-invert', 'use the outside of the matte'),
      n('feather', 'soften the matte edge, px (0..40)'),
      n('choke', 'shrink the matte edge by px (negative grows it)'),
      b('bypass', 'switch the effect off (kept in the stack)'),
      b('enable', 'switch it back on'),
      s('region', 'blur region x,y,w,h'),
      n('strength', 'blur strength'),
    ],
  }),
  cmd({
    name: 'fx.remove',
    module: 'fx',
    writes: true,
    summary: 'Remove an effect, with its keyframes, in one undoable step. The source file is not touched. --all removes every video effect.',
    usage: 'studio fx remove --clip c_xx (--node f_xxxx | --all)',
    example: 'studio fx remove --clip c_01 --node f_k3f9',
    flags: [s('clip', 'media clip id', true), s('node', 'effect id or position'), b('all', 'remove every video effect on the clip')],
  }),
  cmd({
    name: 'fx.move',
    module: 'fx',
    writes: true,
    summary: 'Change the order of effects (order matters: each one works on the result of the one before).',
    usage: 'studio fx move --clip c_xx --node f_xxxx --to POSITION',
    example: 'studio fx move --clip c_01 --node f_k3f9 --to 0',
    flags: [s('clip', 'media clip id', true), s('node', 'effect id or position', true), n('to', 'new position', true)],
  }),
  cmd({
    name: 'fx.bypass',
    module: 'fx',
    writes: true,
    summary: 'Switch an effect off (it stays in the stack) or back on with --off; compare with and without it.',
    usage: 'studio fx bypass --clip c_xx --node f_xxxx [--off]',
    example: 'studio fx bypass --clip c_01 --node f_k3f9',
    flags: [s('clip', 'media clip id', true), s('node', 'effect id or position', true), b('off', 'switch it back on')],
  }),
  cmd({
    name: 'fx.key',
    module: 'fx',
    writes: true,
    summary: 'Keyframe one parameter of an effect (any number parameter, `mix` for how much of the effect shows, or the `db` of a gain). --delete k_id removes a keyframe.',
    usage: 'studio fx key --clip c_xx --node f_xxxx --param NAME --t MS --v N [--ease expo.out] | --delete k_xxxx',
    example: 'studio fx key --clip c_01 --node f_k3f9 --param exposure --t 1000 --v 1.5 --ease sine.inOut',
    flags: [
      s('clip', 'media clip id', true),
      s('node', 'effect id or position'),
      s('param', 'parameter name, or mix'),
      n('t', 'ms from the clip start'),
      n('v', 'value'),
      s('ease', 'easing name'),
      s('delete', 'keyframe id to delete'),
    ],
  }),
  cmd({
    name: 'track.add',
    module: 'track',
    writes: true,
    summary: 'Follow a flat region of a video through time (planar tracking). Analyses the frames, stores one homography per frame in the cache, and defines the tracker in the project. Look at the result with `track preview`.',
    usage: 'studio track add --asset a_xx [--box x,y,w,h | --quad x1,y1,x2,y2,x3,y3,x4,y4] [--at MS] [--from MS --to MS] [--model homography|affine|similarity|translation] [--no-refine] [--fps N] [--width N] [--label T] [--no-build]',
    example: 'studio track add --asset a_01 --box 0.3,0.2,0.4,0.3 --at 1500',
    flags: [
      s('asset', 'video asset id', true),
      s('box', 'region as x,y,w,h, fractions of the frame (default: the whole frame inset 6%)'),
      s('quad', 'region as 8 numbers, corners clockwise from the top left'),
      n('at', 'reference frame (ms of the asset) where the region is drawn; default --from'),
      n('from', 'first ms to analyse (default 0)'),
      n('to', 'last ms to analyse (default: the end)'),
      s('model', 'motion model: homography (default), affine, similarity, translation, or plane3d (solve the camera in 3D and follow the plane through it)'),
      n('focal-deg', 'plane3d: the lens’s horizontal field of view in degrees, as a starting value (default 58)'),
      b('fix-focal', 'plane3d: keep --focal-deg as given instead of refining it'),
      b('no-refine', 'skip aligning the reference picture to each frame (faster; the path drifts more)'),
      n('fps', 'analysis frame rate (default: the source rate up to 30)'),
      n('width', 'analysis width in px (default 480)'),
      s('label', 'a name for the tracker'),
      b('no-build', 'only define it; build later with track build'),
    ],
  }),
  cmd({
    name: 'track.build',
    module: 'track',
    fn: 'buildCmd',
    writes: false,
    summary: 'Analyse a tracker (or read its cached analysis). Renders do this by themselves when it is missing; --force redoes it.',
    usage: 'studio track build tk_xxxx [--force]',
    example: 'studio track build tk_k3f9',
    flags: [s('tracker', 'tracker id (or give it as the first argument)')],
  }),
  cmd({
    name: 'track.list',
    module: 'track',
    writes: false,
    summary: 'Every tracker: its asset, range and model, whether it has been analysed (frames followed and lost), and which clips use it.',
    usage: 'studio track list',
    example: 'studio track list',
    flags: [],
  }),
  cmd({
    name: 'track.show',
    module: 'track',
    writes: false,
    summary: 'Where the tracked region is across the analysed frames (corner positions as fractions of the frame), sampled every N frames, with the lost ranges.',
    usage: 'studio track show tk_xxxx [--every N]',
    example: 'studio track show tk_k3f9 --every 10',
    flags: [s('tracker', 'tracker id'), n('every', 'sample every N analysed frames')],
  }),
  cmd({
    name: 'track.set',
    module: 'track',
    writes: true,
    summary: 'Change a tracker (region, range, reference frame, model) and re-analyse it. Clips that use it follow the change.',
    usage: 'studio track set tk_xxxx [--box ... | --quad ...] [--from MS] [--to MS] [--at MS] [--model M] [--refine | --no-refine] [--fps N] [--width N] [--label T] [--no-build]',
    example: 'studio track set tk_k3f9 --box 0.35,0.25,0.3,0.25',
    flags: [
      s('tracker', 'tracker id'), s('box', 'region x,y,w,h'), s('quad', 'region as 8 numbers'), n('from', 'first ms'), n('to', 'last ms'), n('at', 'reference ms'),
      s('model', 'motion model'), n('focal-deg', 'plane3d: horizontal field of view in degrees'), b('fix-focal', 'plane3d: keep it fixed'), b('refine', 'align to the reference picture'), b('no-refine', 'do not'), n('fps', 'analysis rate'), n('width', 'analysis width'), s('label', 'name'), b('no-build', 'do not re-analyse now'),
    ],
  }),
  cmd({
    name: 'track.remove',
    module: 'track',
    writes: true,
    summary: 'Remove a tracker (refused while a stabilize or pin effect uses it).',
    usage: 'studio track remove tk_xxxx',
    example: 'studio track remove tk_k3f9',
    flags: [s('tracker', 'tracker id')],
  }),
  cmd({
    name: 'track.preview',
    module: 'track',
    writes: false,
    summary: 'A contact sheet (PNG) of frames across the track with the tracked region outlined on each: how to check by eye that it stayed on its plane. Yellow = reference frame, green = followed, red = lost.',
    usage: 'studio track preview tk_xxxx [--frames 6]',
    example: 'studio track preview tk_k3f9 --frames 9',
    flags: [s('tracker', 'tracker id'), n('frames', 'how many frames (2..12, default 6)')],
  }),
  cmd({
    name: 'track.solve',
    module: 'track',
    writes: false,
    summary: '3D camera tracking: solve where the camera is, and how it is turned, in every frame of a shot, plus a sparse cloud of 3D points, from the picture alone. Needs a camera that moves through space (not only pans). Reports the focal length it found and how well the points reproject; --out writes the camera path as JSON for other tools, --preview draws the solved points on frames.',
    usage: 'studio track solve --asset a_xx [--from MS] [--to MS] [--fps N] [--width N] [--focal-deg D] [--fix-focal] [--out renders/camera.json] [--preview] [--frames N] [--force]',
    example: 'studio track solve --asset a_01 --out renders/camera.json --preview',
    flags: [
      s('asset', 'video asset id', true),
      n('from', 'first ms (default 0)'),
      n('to', 'last ms (default: the end)'),
      n('fps', 'analysis frame rate (default: the source rate up to 30)'),
      n('width', 'analysis width in px (default 480)'),
      n('focal-deg', 'the lens’s horizontal field of view in degrees, as a starting value (default 58)'),
      b('fix-focal', 'keep --focal-deg as given instead of refining it'),
      s('out', 'write the camera path and points as JSON to this path inside the project'),
      b('preview', 'also write a contact sheet with the solved points drawn on frames'),
      n('frames', 'frames on the sheet (2..12, default 6)'),
    ],
  }),
  cmd({
    name: 'stabilize',
    module: 'track',
    writes: true,
    summary: 'Steady shaky footage on a clip: tracks the camera motion, smooths it (or holds the first frame), and warps every frame by the difference, enlarged just enough to hide the borders. A non-destructive effect: change it with `fx set`, switch it off with `fx bypass`.',
    usage: 'studio stabilize --clip c_xx [--smooth SECONDS] [--lock] [--max-zoom 1.25] [--tracker tk_xx | --box x,y,w,h] [--model M] [--refine] [--width N]',
    example: 'studio stabilize --clip c_01 --smooth 0.8',
    flags: [
      s('clip', 'media clip id', true),
      n('smooth', 'seconds of camera motion to keep (0.05..30, default 0.6); smaller = steadier'),
      b('lock', 'hold the picture still on the first frame (a locked-off look) instead of smoothing'),
      n('max-zoom', 'most the picture may be enlarged to hide borders (1..2, default 1.25)'),
      s('tracker', 'reuse an existing tracker (made on this clip’s asset)'),
      s('box', 'follow this part of the frame only (x,y,w,h), e.g. the background without a moving subject'),
      s('model', 'motion model (default homography)'),
      b('refine', 'also align to the reference picture (only for a flat, always-visible region)'),
      n('width', 'analysis width in px (default 480)'),
    ],
  }),
  cmd({
    name: 'pin',
    module: 'track',
    writes: true,
    summary: 'Fix an image or video onto a tracked plane (corner pin): it follows the plane’s four corners through every frame. Give a tracker, or the region of the plane at a reference frame.',
    usage: 'studio pin --clip c_xx --asset a_img (--tracker tk_xx | --box x,y,w,h | --quad ...) [--at MS] [--place x,y,w,h | --place-quad ...] [--opacity 0..1]',
    example: 'studio pin --clip c_01 --asset a_logo --quad 0.31,0.22,0.62,0.25,0.6,0.5,0.3,0.46 --at 1000',
    flags: [
      s('clip', 'media clip id', true),
      s('asset', 'the image or video to pin (already ingested)', true),
      s('tracker', 'an existing tracker'),
      s('box', 'the plane as x,y,w,h at the reference frame'),
      s('quad', 'the plane as 8 numbers, clockwise from the top left'),
      n('at', 'reference frame in ms of the source (default: the clip start)'),
      s('place', 'where on the plane the graphic goes, x,y,w,h (default: the whole tracked region)'),
      s('place-quad', 'same, as 8 numbers'),
      n('opacity', '0..1'),
      s('model', 'motion model (default homography)'),
      b('no-refine', 'skip aligning to the reference picture'),
      n('width', 'analysis width in px'),
    ],
  }),
  cmd({
    name: 'mask.pick',
    module: 'matte',
    fn: 'maskPick',
    writes: false,
    summary: 'Try the Object Mask Tool on one frame without storing anything: the segmenter\'s three candidate masks for your points (--point on the object, --neg off it) and box, side by side in one picture, with which one `auto` would take and whether each keeps your points inside and outside. Correct the points until one candidate is the object, then `mask add`.',
    usage: 'studio mask pick --asset a_xx --at MS (--point "x,y" | --neg "x,y" | --box x,y,w,h) [--px] [--width N]',
    example: 'studio mask pick --asset a_01 --at 0 --point "0.62,0.4" --neg "0.8,0.8" --box 0.1,0,0.85,1',
    flags: [
      s('asset', 'video asset id', true),
      n('at', 'the frame, in ms of the asset (default 0)'),
      s('point', 'dots ON the object: "x,y|x,y"'),
      s('neg', 'dots on what must NOT be part of it: "x,y|x,y"'),
      s('box', 'the object lies inside this box: x,y,w,h'),
      s('outline', 'a rough outline of the object'),
      b('px', 'coordinates are pixels of the video frame instead of fractions'),
      n('width', 'analysis width in px (default 480)'),
    ],
  }),
  cmd({
    name: 'mask.add',
    module: 'matte',
    fn: 'maskAdd',
    writes: true,
    summary: 'The Object Mask Tool: select an object by clicking on it. Look at a frame, give points on the object (--point), points on what must NOT be included (--neg), or a box; the segmenter (Segment Anything 2.1, runs locally on the CPU) finds exactly that object, whether it is a person, a phone, a bottle or a logo, and Studio follows it through the shot. Add more points with `mask key --add` to include a missed part or exclude a wrongly included one; use it as a cutout, to remove the background, or to limit any effect to the object. The first build encodes every frame once (about 1 to 2 s each, then cached).',
    usage: 'studio mask add --asset a_xx --at MS (--point "x,y;x,y" | --neg "x,y" | --box x,y,w,h) [--pick whole|best|first] [--from MS --to MS] [--px] [--fps N] [--width N] [--label T] [--no-build]',
    example: 'studio mask add --asset a_01 --at 0 --point "0.93,0.08" --neg "0.5,0.5"',
    flags: [
      s('asset', 'video asset id', true),
      n('at', 'the frame you mark, in ms of the asset (default --from)'),
      n('from', 'first ms to cut out (default 0)'),
      n('to', 'last ms (default the end)'),
      s('point', 'dots ON the object: "x,y|x,y" (fractions of the frame, or pixels with --px)'),
      s('neg', 'dots on what must NOT be part of it: "x,y|x,y"'),
      s('pick', 'which of the segmenter\'s three candidates: auto (default: the one that keeps your points inside and outside as asked), whole (the largest), best (its own quality guess), first'),
      s('box', 'the object lies inside this box: x,y,w,h'),
      s('fg', 'dots or strokes ON the object: "x,y;x,y|x,y" (| separates strokes)'),
      s('fg-fill', 'filled areas on the object: "x,y;x,y;x,y|..." (closed polygons)'),
      s('bg', 'dots or strokes on what is NOT the object'),
      s('bg-fill', 'filled areas that are not the object'),
      s('outline', 'a rough outline of the object, a closed polygon "x,y;x,y;x,y;..."; only a ring around it is decided from the picture'),
      n('band', 'how far off the outline may be, a fraction of the width (default 0.025), or pixels with --px'),
      n('radius', 'stroke radius, a fraction of the width (default 0.006), or pixels with --px'),
      b('px', 'coordinates are pixels of the video frame instead of fractions'),
      s('seeds', 'all the marks as JSON (box, fg, bg, outline)'),
      s('prior', 'a saliency model\'s guess as extra evidence: u2net or u2netp (needs the python models; marks alone work without)'),
      s('engine', 'what decides the boundary: auto (default: the u2net saliency model guided by your marks when it can run, else marks and colours), u2net, u2netp, colour (marks and colours alone)'),
      n('edge-width', 'width of the finished matte in px (default the source\'s, up to 960): the edge is decided from the picture at this size'),
      b('no-refine', 'skip deciding the edge again from the full-resolution picture'),
      b('hair', 'a wider edge band where there is fine detail around the boundary (hair)'),
      n('smooth', 'flicker control 0..1 (default 0.7): steady the matte over time along the motion'),
      b('no-smooth', 'no flicker control'),
      b('no-decontaminate', 'do not take the old background out of the edge pixels\' colour'),
      s('edge-model', 'vitmatte: a trained matting model decides the opacity in the edge band (hair, fur, fine detail; about 0.5 to 2 s a frame; `studio models fetch vitmatte-small`)'),
      n('fps', 'analysis frame rate (default: the source rate up to 30)'),
      n('width', 'analysis width in px (default 480)'),
      s('label', 'a name'),
      b('no-build', 'only define it; build later with matte build'),
    ],
  }),
  cmd({
    name: 'mask.key',
    module: 'matte',
    fn: 'maskKey',
    writes: true,
    summary: 'Mark another frame of a matte where it has drifted or the object changed (or add marks to a marked frame with --add), then follow again: the matte is followed from each marked frame to the next, from both sides, so a few marks fix a long stretch.',
    usage: 'studio mask key mt_xxxx --at MS (--point ... | --neg ... | --box ...) [--add] [--pick whole|best|first] [--px] [--no-build]',
    example: 'studio mask key mt_k3f9 --at 1000 --neg "0.2,0.5" --add',
    flags: [
      s('matte', 'matte id (or the first argument)'),
      n('at', 'the frame you mark, in ms of the asset', true),
      s('point', 'dots ON the object: "x,y|x,y"'),
      s('neg', 'dots on what must NOT be part of it: "x,y|x,y"'),
      s('pick', 'whole, best or first candidate'),
      s('box', 'the object lies inside this box: x,y,w,h'),
      s('fg', 'dots or strokes ON the object: "x,y;x,y|x,y" (| separates strokes)'),
      s('fg-fill', 'filled areas on the object: "x,y;x,y;x,y|..." (closed polygons)'),
      s('bg', 'dots or strokes on what is NOT the object'),
      s('bg-fill', 'filled areas that are not the object'),
      s('outline', 'a rough outline of the object, a closed polygon "x,y;x,y;x,y;..."; only a ring around it is decided from the picture'),
      n('band', 'how far off the outline may be, a fraction of the width (default 0.025), or pixels with --px'),
      n('radius', 'stroke radius, a fraction of the width (default 0.006), or pixels with --px'),
      b('px', 'coordinates are pixels of the video frame instead of fractions'),
      s('seeds', 'all the marks as JSON (box, fg, bg, outline)'),
      s('prior', 'a saliency model\'s guess as extra evidence: u2net or u2netp (needs the python models; marks alone work without)'),
      b('add', 'add these marks to the ones already on that frame instead of replacing them'),
      b('no-build', 'do not follow again now'),
    ],
  }),
  cmd({
    name: 'mask.preview',
    module: 'matte',
    writes: false,
    summary: 'A contact sheet (PNG) to look at: for each frame, the picture with the matte tinted and outlined (marks drawn on marked frames) and the cut-out on a checkerboard. The way to find where a matte drifts.',
    usage: 'studio mask preview mt_xxxx [--frames 4] [--at MS,MS,...]',
    example: 'studio mask preview mt_k3f9 --at 500,1500,2500,3500',
    flags: [s('matte', 'matte id'), n('frames', 'how many frames (2..8, default 4)'), s('at', 'specific times in ms of the asset, comma separated')],
  }),
  cmd({
    name: 'mask.build',
    module: 'matte',
    fn: 'buildCmd',
    writes: false,
    summary: 'Follow the object through the shot (or read the cached result). Renders do this by themselves when it is missing; --force redoes it.',
    usage: 'studio mask build mt_xxxx [--force]',
    example: 'studio mask build mt_k3f9',
    flags: [s('matte', 'matte id (or the first argument)')],
  }),
  cmd({
    name: 'mask.list',
    module: 'matte',
    writes: false,
    summary: 'Every matte: asset, range, marked frames, whether it is built, its coverage, how many frames to check, and which clips use it.',
    usage: 'studio mask list',
    example: 'studio mask list',
    flags: [],
  }),
  cmd({
    name: 'mask.remove',
    module: 'matte',
    writes: true,
    summary: 'Remove a matte (refused while a cutout or an effect uses it).',
    usage: 'studio mask remove mt_xxxx',
    example: 'studio mask remove mt_k3f9',
    flags: [s('matte', 'matte id')],
  }),
  cmd({
    name: 'mask.export',
    module: 'matte',
    fn: 'exportCmd',
    writes: false,
    summary: 'Copy the matte as a gray lossless video (FFV1 in Matroska) into the project, for other tools.',
    usage: 'studio mask export mt_xxxx [--out renders/matte.mkv]',
    example: 'studio mask export mt_k3f9 --out renders/subject-matte.mkv',
    flags: [s('matte', 'matte id'), s('out', 'path inside the project folder')],
  }),
  cmd({
    name: 'matte.add',
    module: 'matte',
    writes: true,
    summary: 'Cut an object out of a video without a green screen (Roto Brush / Magic Mask style). You look at a frame and mark the object (a box, dots and strokes on it and on what is not it, or a rough outline); Studio cuts it out of that frame and follows it through the shot with optical flow, deciding only a band around the edge on each frame from the colours and edges. Look at the result with `matte preview`.',
    usage: 'studio matte add --asset a_xx [--at MS] [--from MS --to MS] (--box x,y,w,h | --fg "x,y;x,y" | --bg "x,y" | --outline "x,y;x,y;x,y" | --seeds JSON) [--px] [--prior u2net] [--engine auto|colour|u2net|u2netp] [--fps N] [--width N] [--label T] [--no-build]',
    example: 'studio matte add --asset a_01 --at 1200 --box 0.3,0.1,0.35,0.8 --fg "0.47,0.4"',
    flags: [
      s('asset', 'video asset id', true),
      n('at', 'the frame you mark, in ms of the asset (default --from)'),
      n('from', 'first ms to cut out (default 0)'),
      n('to', 'last ms (default the end)'),
      s('box', 'the object lies inside this box: x,y,w,h'),
      s('fg', 'dots or strokes ON the object: "x,y;x,y|x,y" (| separates strokes)'),
      s('fg-fill', 'filled areas on the object: "x,y;x,y;x,y|..." (closed polygons)'),
      s('bg', 'dots or strokes on what is NOT the object'),
      s('bg-fill', 'filled areas that are not the object'),
      s('outline', 'a rough outline of the object, a closed polygon "x,y;x,y;x,y;..."; only a ring around it is decided from the picture'),
      n('band', 'how far off the outline may be, a fraction of the width (default 0.025), or pixels with --px'),
      n('radius', 'stroke radius, a fraction of the width (default 0.006), or pixels with --px'),
      b('px', 'coordinates are pixels of the video frame instead of fractions'),
      s('seeds', 'all the marks as JSON (box, fg, bg, outline)'),
      s('prior', 'a saliency model\'s guess as extra evidence: u2net or u2netp (needs the python models; marks alone work without)'),
      s('engine', 'what decides the boundary: auto (default: the u2net saliency model guided by your marks when it can run, else marks and colours), u2net, u2netp, colour (marks and colours alone), sam (the promptable segmenter: see `studio mask add`)'),
      n('edge-width', 'width of the finished matte in px (default the source\'s, up to 960): the edge is decided from the picture at this size'),
      b('no-refine', 'skip deciding the edge again from the full-resolution picture'),
      b('hair', 'a wider edge band where there is fine detail around the boundary (hair)'),
      n('smooth', 'flicker control 0..1 (default 0.7): steady the matte over time along the motion'),
      b('no-smooth', 'no flicker control'),
      b('no-decontaminate', 'do not take the old background out of the edge pixels\' colour'),
      s('edge-model', 'vitmatte: a trained matting model decides the opacity in the edge band (hair, fur, fine detail; about 0.5 to 2 s a frame; `studio models fetch vitmatte-small`)'),
      n('fps', 'analysis frame rate (default: the source rate up to 30)'),
      n('width', 'analysis width in px (default 480)'),
      s('label', 'a name'),
      b('no-build', 'only define it; build later with matte build'),
    ],
  }),
  cmd({
    name: 'matte.key',
    module: 'matte',
    writes: true,
    summary: 'Mark another frame of a matte where it has drifted or the object changed (or add marks to a marked frame with --add), then follow again: the matte is followed from each marked frame to the next, from both sides, so a few marks fix a long stretch.',
    usage: 'studio matte key mt_xxxx --at MS (--box ... | --fg ... | --bg ... | --outline ...) [--add] [--px] [--prior u2net] [--no-build]',
    example: 'studio matte key mt_k3f9 --at 3400 --bg "0.2,0.5;0.22,0.55" --add',
    flags: [
      s('matte', 'matte id (or the first argument)'),
      n('at', 'the frame you mark, in ms of the asset', true),
      s('box', 'the object lies inside this box: x,y,w,h'),
      s('fg', 'dots or strokes ON the object: "x,y;x,y|x,y" (| separates strokes)'),
      s('fg-fill', 'filled areas on the object: "x,y;x,y;x,y|..." (closed polygons)'),
      s('bg', 'dots or strokes on what is NOT the object'),
      s('bg-fill', 'filled areas that are not the object'),
      s('outline', 'a rough outline of the object, a closed polygon "x,y;x,y;x,y;..."; only a ring around it is decided from the picture'),
      n('band', 'how far off the outline may be, a fraction of the width (default 0.025), or pixels with --px'),
      n('radius', 'stroke radius, a fraction of the width (default 0.006), or pixels with --px'),
      b('px', 'coordinates are pixels of the video frame instead of fractions'),
      s('seeds', 'all the marks as JSON (box, fg, bg, outline)'),
      s('prior', 'a saliency model\'s guess as extra evidence: u2net or u2netp (needs the python models; marks alone work without)'),
      b('add', 'add these marks to the ones already on that frame instead of replacing them'),
      b('no-build', 'do not follow again now'),
    ],
  }),
  cmd({
    name: 'matte.edge',
    module: 'matte',
    fn: 'edge',
    writes: true,
    summary: 'Change how the edge of a matte (or object mask) is made, then build it again: the resolution of the finished matte, whether the boundary is decided again from the full-resolution picture, a wider band for hair, the flicker control, and cleaning the old background out of the edge colour. Look with `matte preview` (and the cut-out over green and over white) and read `result.edge` for the measured flicker.',
    usage: 'studio matte edge mt_xxxx [--edge-width N] [--hair] [--no-refine] [--smooth 0..1 | --no-smooth] [--no-decontaminate] [--reset] [--no-build]',
    example: 'studio matte edge mt_k3f9 --hair --edge-width 1280',
    flags: [
      s('matte', 'matte id (or the first argument)'),
      n('edge-width', 'width of the finished matte in px'),
      b('no-refine', 'skip deciding the edge again from the picture'),
      b('hair', 'a wider band for fine detail (hair)'),
      n('smooth', 'flicker control 0..1'),
      b('no-smooth', 'no flicker control'),
      b('no-decontaminate', 'do not clean the edge colour'),
      s('edge-model', 'vitmatte, or none to go back to the guided filter'),
      b('reset', 'back to the defaults'),
      b('no-build', 'do not build again now'),
    ],
  }),
  cmd({
    name: 'mask.edge',
    module: 'matte',
    fn: 'edge',
    writes: true,
    summary: 'Change how the edge of a matte (or object mask) is made, then build it again: the resolution of the finished matte, whether the boundary is decided again from the full-resolution picture, a wider band for hair, the flicker control, and cleaning the old background out of the edge colour. Look with `matte preview` (and the cut-out over green and over white) and read `result.edge` for the measured flicker.',
    usage: 'studio mask edge mt_xxxx [--edge-width N] [--hair] [--no-refine] [--smooth 0..1 | --no-smooth] [--no-decontaminate] [--reset] [--no-build]',
    example: 'studio mask edge mt_k3f9 --hair --edge-width 1280',
    flags: [
      s('matte', 'matte id (or the first argument)'),
      n('edge-width', 'width of the finished matte in px'),
      b('no-refine', 'skip deciding the edge again from the picture'),
      b('hair', 'a wider band for fine detail (hair)'),
      n('smooth', 'flicker control 0..1'),
      b('no-smooth', 'no flicker control'),
      b('no-decontaminate', 'do not clean the edge colour'),
      b('reset', 'back to the defaults'),
      b('no-build', 'do not build again now'),
    ],
  }),
  cmd({
    name: 'matte.unkey',
    module: 'matte',
    writes: true,
    summary: 'Remove the marks of one frame of a matte and follow again.',
    usage: 'studio matte unkey mt_xxxx --at MS',
    example: 'studio matte unkey mt_k3f9 --at 3400',
    flags: [s('matte', 'matte id'), n('at', 'the marked frame, ms', true), b('no-build', 'do not follow again now')],
  }),
  cmd({
    name: 'matte.build',
    module: 'matte',
    fn: 'buildCmd',
    writes: false,
    summary: 'Follow the object through the shot (or read the cached result). Renders do this by themselves when it is missing; --force redoes it.',
    usage: 'studio matte build mt_xxxx [--force]',
    example: 'studio matte build mt_k3f9',
    flags: [s('matte', 'matte id (or the first argument)')],
  }),
  cmd({
    name: 'matte.list',
    module: 'matte',
    writes: false,
    summary: 'Every matte: asset, range, marked frames, whether it is built, its coverage, how many frames to check, and which clips use it.',
    usage: 'studio matte list',
    example: 'studio matte list',
    flags: [],
  }),
  cmd({
    name: 'matte.show',
    module: 'matte',
    writes: false,
    summary: 'A matte in numbers: how much of the picture it covers over time, how well following agrees with the marked frames (IoU), and the frames to check (area jumps, an empty matte, an undecided boundary).',
    usage: 'studio matte show mt_xxxx',
    example: 'studio matte show mt_k3f9',
    flags: [s('matte', 'matte id')],
  }),
  cmd({
    name: 'matte.preview',
    module: 'matte',
    writes: false,
    summary: 'A contact sheet (PNG) to look at: for each frame, the picture with the matte tinted and outlined (marks drawn on marked frames) and the cut-out on a checkerboard. The way to find where a matte drifts.',
    usage: 'studio matte preview mt_xxxx [--frames 4] [--at MS,MS,...]',
    example: 'studio matte preview mt_k3f9 --at 500,1500,2500,3500',
    flags: [s('matte', 'matte id'), n('frames', 'how many frames (2..8, default 4)'), s('at', 'specific times in ms of the asset, comma separated')],
  }),
  cmd({
    name: 'matte.remove',
    module: 'matte',
    writes: true,
    summary: 'Remove a matte (refused while a cutout or an effect uses it).',
    usage: 'studio matte remove mt_xxxx',
    example: 'studio matte remove mt_k3f9',
    flags: [s('matte', 'matte id')],
  }),
  cmd({
    name: 'matte.export',
    module: 'matte',
    fn: 'exportCmd',
    writes: false,
    summary: 'Copy the matte as a gray lossless video (FFV1 in Matroska) into the project, for other tools.',
    usage: 'studio matte export mt_xxxx [--out renders/matte.mkv]',
    example: 'studio matte export mt_k3f9 --out renders/subject-matte.mkv',
    flags: [s('matte', 'matte id'), s('out', 'path inside the project folder')],
  }),
  cmd({
    name: 'cutout',
    module: 'matte',
    writes: true,
    summary: 'Make a clip transparent everywhere but the object (or only the object, with --invert): tracks below show through. Give an existing --matte, or the marks to make one on the spot. A non-destructive effect; change it with `fx set`, switch it off with `fx bypass`.',
    usage: 'studio cutout --clip c_xx (--matte mt_xx | --box ... --fg ... [--at MS]) [--invert] [--feather PX] [--choke PX]',
    example: 'studio cutout --clip c_01 --box 0.3,0.1,0.35,0.8 --at 1200 --feather 1.5',
    flags: [
      s('clip', 'media clip id', true),
      s('matte', 'an existing matte (made on this clip’s asset)'),
      n('at', 'the frame you mark (ms of the asset) when making a matte'),
      s('box', 'the object lies inside this box: x,y,w,h'),
      s('fg', 'dots or strokes ON the object: "x,y;x,y|x,y" (| separates strokes)'),
      s('fg-fill', 'filled areas on the object: "x,y;x,y;x,y|..." (closed polygons)'),
      s('bg', 'dots or strokes on what is NOT the object'),
      s('bg-fill', 'filled areas that are not the object'),
      s('outline', 'a rough outline of the object, a closed polygon "x,y;x,y;x,y;..."; only a ring around it is decided from the picture'),
      n('band', 'how far off the outline may be, a fraction of the width (default 0.025), or pixels with --px'),
      n('radius', 'stroke radius, a fraction of the width (default 0.006), or pixels with --px'),
      b('px', 'coordinates are pixels of the video frame instead of fractions'),
      s('seeds', 'all the marks as JSON (box, fg, bg, outline)'),
      s('prior', 'a saliency model\'s guess as extra evidence: u2net or u2netp (needs the python models; marks alone work without)'),
      s('engine', 'what decides the boundary: auto (default: the u2net saliency model guided by your marks when it can run, else marks and colours), u2net, u2netp, colour (marks and colours alone)'),
      b('invert', 'keep everything except the object'),
      n('feather', 'soften the edge, px (0..40)'),
      n('choke', 'shrink the edge by px (negative grows it)'),
    ],
  }),
];
