import type { FlagDef } from './args.js';

export interface CmdMeta {
  name: string;
  argv: string[];
  summary: string;
  usage: string;
  example: string;
  flags: FlagDef[];
  writes: boolean;
  /** Module loaded on demand, so `studio tools` never imports zod or an engine. */
  module:
    | 'tools'
    | 'project'
    | 'ops'
    | 'tl'
    | 'doctor'
    | 'ingest'
    | 'cache'
    | 'render'
    | 'inspect'
    | 'ui'
    | 'video'
    | 'audio'
    | 'image'
    | 'models'
    | 'motion'
    | 'captions'
    | 'mcp';
  fn: string;
}

const s = (name: string, desc: string, required = false): FlagDef => ({
  name,
  type: 'string',
  desc,
  required,
});
const n = (name: string, desc: string, required = false): FlagDef => ({
  name,
  type: 'number',
  desc,
  required,
});
const b = (name: string, desc: string): FlagDef => ({ name, type: 'boolean', desc });
const cmd = (c: Omit<CmdMeta, 'argv' | 'fn'> & { fn?: string }): CmdMeta => ({
  ...c,
  argv: c.name.split('.'),
  fn:
    c.fn ??
    c.name
      .split('.')
      .pop()!
      .replace(/-./g, (m) => m[1]!.toUpperCase()),
});

/** The single source of the command surface. `studio tools` is generated from this list. */
export const COMMANDS: CmdMeta[] = [
  cmd({
    name: 'tools',
    module: 'tools',
    writes: false,
    summary: 'List every implemented command with flags and an example.',
    usage: 'studio tools [--json]',
    example: 'studio tools',
    flags: [],
  }),
  cmd({
    name: 'doctor',
    module: 'doctor',
    writes: false,
    summary: 'Check node, ffmpeg, encoders (by test-encoding), disk, and models.',
    usage: 'studio doctor',
    example: 'studio doctor',
    flags: [],
  }),
  cmd({
    name: 'init',
    module: 'project',
    writes: true,
    summary: 'Create a project in the project directory.',
    usage: 'studio init <name> [--width N --height N --fps N --background #rrggbb]',
    example: 'studio init "Demo v2" --width 1920 --height 1080 --fps 30',
    flags: [
      n('width', 'canvas width'),
      n('height', 'canvas height'),
      n('fps', 'project frame rate'),
      s('background', 'sRGB hex'),
    ],
  }),
  cmd({
    name: 'ingest',
    module: 'ingest',
    writes: true,
    summary: 'Probe, hash, copy into assets/, register as assets; derive proxy, thumbnails, peaks.',
    usage: 'studio ingest <path...> [--sync] [--no-derive]',
    example: 'studio ingest ~/rec.mp4 --sync',
    flags: [
      b('sync', 'build proxy/thumbs/peaks now instead of in a background process'),
      b('no-derive', 'skip proxy/thumbs/peaks (run `studio cache build` later)'),
      s('label', 'log label'),
    ],
  }),
  cmd({
    name: 'cache.build',
    module: 'cache',
    writes: true,
    summary: 'Build missing proxy, thumbnails, and peaks (resumable; skips finished artifacts).',
    usage: 'studio cache build [--assets a_x,a_y]',
    example: 'studio cache build',
    flags: [s('assets', 'comma-separated asset ids (default: all)')],
  }),
  cmd({
    name: 'render',
    module: 'render',
    writes: true,
    summary:
      'Render the timeline: FFmpeg, or hybrid FFmpeg + motion renderer when composition clips exist (two-pass loudness, safe write, versioned name).',
    usage:
      'studio render [--preset ID] [--range A:B] [--preview] [--still MS] [--out NAME] [--explain]',
    example: 'studio render --preset youtube-1080p',
    flags: [
      s(
        'preset',
        'youtube-1080p (default), youtube-4k, vertical-1080x1920, square-1080, portrait-4x5, gif-small, overlay-alpha (composition clips only, transparent)',
      ),
      s('range', 'timeline range in ms, A:B'),
      b('preview', 'fast low-resolution render'),
      n('still', 'one PNG frame at this timeline ms'),
      s('out', 'output base name (default: <project>-<preset>-vN)'),
      s('encoder', 'video encoder (libx264 only for now)'),
      b('no-normalize', 'skip loudness normalization'),
      n('width', 'render at this width (height follows the aspect)'),
      {
        name: 'reframe',
        type: 'string',
        desc: 'fit (default), blur, center-crop',
        values: ['fit', 'blur', 'center-crop'],
      },
      s('x264-preset', 'x264 preset override, e.g. veryfast'),
      s('alpha-format', 'overlay-alpha only: prores4444 (default) or webm'),
      s('export', 'use preset and reframe from a recorded export id'),
      b('explain', 'print the plan and ffmpeg arguments, run nothing'),
    ],
  }),
  cmd({
    name: 'inspect.frame',
    module: 'inspect',
    writes: true,
    summary: "Extract PNG frames at times (ms). Also reports each frame's mean colour.",
    usage: 'studio inspect frame <file> --at MS[,MS...] [--width N]',
    example: 'studio inspect frame renders/demo-youtube-1080p-v1.mp4 --at 0,1500,4000',
    flags: [s('at', 'comma-separated times in ms', true), n('width', 'scale to this width')],
  }),
  cmd({
    name: 'inspect.sheet',
    module: 'inspect',
    writes: true,
    summary: 'Contact sheets, at most 24 tiles each, with tile times.',
    usage: 'studio inspect sheet <file> [--fps N] [--cols N] [--width N]',
    example: 'studio inspect sheet renders/demo-youtube-1080p-v1.mp4 --fps 1 --cols 6 --width 320',
    flags: [
      n('fps', 'tiles per second (default 1)'),
      n('cols', 'columns (default 6)'),
      n('width', 'tile width px (default 320)'),
    ],
  }),
  cmd({
    name: 'inspect.waveform',
    module: 'inspect',
    writes: true,
    summary: 'Waveform PNG of the audio.',
    usage: 'studio inspect waveform <file>',
    example: 'studio inspect waveform assets/vo.wav',
    flags: [],
  }),
  cmd({
    name: 'inspect.loudness',
    module: 'inspect',
    writes: false,
    summary: 'Integrated LUFS, LRA, true peak, sample peak, noise floor, clipping.',
    usage: 'studio inspect loudness <file> [--from MS] [--to MS]',
    example: 'studio inspect loudness renders/demo-youtube-1080p-v1.mp4',
    flags: [n('from', 'start of the window, ms'), n('to', 'end of the window, ms')],
  }),
  cmd({
    name: 'inspect.silence',
    module: 'inspect',
    writes: false,
    summary: 'Silent spans. Default threshold is the measured noise floor + 8 dB.',
    usage: 'studio inspect silence <file> [--noise-db N] [--min-s S]',
    example: 'studio inspect silence assets/talk.mp4 --min-s 0.4',
    flags: [
      n('noise-db', 'threshold in dB (default: noise floor + 8, between -50 and -20)'),
      n('min-s', 'minimum span in seconds (default 0.4)'),
    ],
  }),
  cmd({
    name: 'inspect.black',
    module: 'inspect',
    writes: false,
    summary: 'Black-frame spans (at least one frame) and frozen spans (at least 1 s).',
    usage: 'studio inspect black <file>',
    example: 'studio inspect black renders/demo-youtube-1080p-v1.mp4',
    flags: [],
  }),
  cmd({
    name: 'inspect.qc',
    module: 'inspect',
    writes: false,
    summary:
      'Technical QC with per-check pass/fail/warn/skipped and measured values. Exits 4 on any failure.',
    usage: 'studio inspect qc <file> [expectation flags]',
    example: 'studio inspect qc renders/demo-youtube-1080p-v1.mp4',
    flags: [
      n('width', 'expected width'),
      n('height', 'expected height'),
      n('fps', 'expected fps'),
      n('duration-ms', 'expected duration'),
      s('expect-audio', 'true|false'),
      n('target-lufs', 'loudness target'),
      n('true-peak-max', 'dBTP ceiling'),
      b('h264', 'check H.264 High/yuv420p/AAC-LC delivery'),
      s('joins', 'join times in ms, comma-separated'),
      s('planned-black', 'intended black/frozen ranges, A:B,A:B'),
      n('max-size-mb', 'file size budget'),
    ],
  }),
  cmd({
    name: 'ui',
    module: 'ui',
    writes: true,
    summary:
      'Serve the UI on localhost, push project changes to it, and accept its edits as ops (actor ui). Stop with Ctrl+C.',
    usage: 'studio ui [--port N] [--read-only]',
    example: 'studio ui --port 4173',
    flags: [
      n('port', 'port (default 4173, 0 = any free port)'),
      b('read-only', 'refuse edits from the page'),
    ],
  }),
  cmd({
    name: 'video.cut-silence',
    module: 'video',
    fn: 'cutSilence',
    writes: true,
    summary:
      'Cut silences out of a clip (pauses are trimmed to the padding, never removed outright). Refuses above 40% removal without --yes.',
    usage:
      'studio video cut-silence --clip C [--noise-db N] [--min-s 0.4] [--pad-ms 100] [--yes] [--no-ripple]',
    example: 'studio video cut-silence --clip c_01 --dry-run',
    flags: [
      s('clip', 'clip id', true),
      n('noise-db', 'threshold in dB (default: measured noise floor + 8, clamped -50..-20)'),
      n('min-s', 'shortest silence to cut, seconds (default 0.4, not lower)'),
      n('pad-ms', 'pause kept next to speech (default 100)'),
      b('yes', 'allow removing more than 40% of the clip'),
      b('no-ripple', 'do not shift later clips on the track'),
    ],
  }),
  cmd({
    name: 'video.scenes',
    module: 'video',
    fn: 'scenes',
    writes: true,
    summary:
      'Scene-change candidates by FFmpeg scene score. Lists times; --apply adds markers (needs --clip). Never cuts.',
    usage: 'studio video scenes (--clip C | --asset A) [--threshold 0.3] [--apply]',
    example: 'studio video scenes --asset a_k3f9 --threshold 0.3',
    flags: [
      s('clip', 'clip id'),
      s('asset', 'asset id'),
      n('threshold', 'scene score 0..1 (default 0.3)'),
      b('apply', 'add timeline markers for each change'),
    ],
  }),
  cmd({
    name: 'video.speed',
    module: 'video',
    fn: 'speed',
    writes: true,
    summary:
      "Change a clip's playback speed. Audio is time-stretched (pitch kept) up to 8x, dropped above.",
    usage: 'studio video speed --clip C --factor F [--ripple]',
    example: 'studio video speed --clip c_03 --factor 4 --ripple',
    flags: [
      s('clip', 'clip id', true),
      n('factor', 'speed factor, 0.1 to 16 (above 1 is faster)', true),
      b('ripple', 'shift later clips on the track by the change in duration'),
    ],
  }),
  cmd({
    name: 'video.reframe',
    module: 'video',
    fn: 'reframe',
    writes: true,
    summary:
      'Record an export for another aspect ratio (fit, blur background, or center crop) and report what it costs.',
    usage:
      'studio video reframe --to vertical|square|portrait-4x5|youtube [--method fit|blur|center-crop] [--id ID] [--still MS]',
    example: 'studio video reframe --to vertical --method blur --still 3000',
    flags: [
      {
        name: 'to',
        type: 'string',
        desc: 'target aspect',
        required: true,
        values: ['vertical', 'square', 'portrait-4x5', 'youtube'],
      },
      {
        name: 'method',
        type: 'string',
        desc: 'how to fit (default fit)',
        values: ['fit', 'blur', 'center-crop'],
      },
      s('id', 'export id (default per target)'),
      n('still', 'also render a still at this timeline ms to check the framing'),
    ],
  }),
  cmd({
    name: 'audio.denoise',
    module: 'audio',
    fn: 'denoise',
    writes: true,
    summary: 'Add a high-pass and denoise to a clip; reports noise floor before and after.',
    usage:
      'studio audio denoise --clip C [--method afftdn|arnndn] [--nr 12] [--nf -50] [--hp 80] [--model FILE]',
    example: 'studio audio denoise --clip c_01 --nr 15',
    flags: [
      s('clip', 'clip id', true),
      {
        name: 'method',
        type: 'string',
        desc: 'afftdn (built in) or arnndn (needs --model)',
        values: ['afftdn', 'arnndn'],
      },
      n('nr', 'noise reduction dB (default 12)'),
      n('nf', 'noise floor dB (default -50)'),
      n('hp', 'high-pass Hz, 0 = none (default 80)'),
      s('model', 'RNNoise model file for arnndn'),
    ],
  }),
  cmd({
    name: 'audio.clean-podcast',
    module: 'audio',
    fn: 'cleanPodcast',
    writes: true,
    summary:
      'Podcast chain: high-pass, denoise, EQ, compressor, limiter, two-pass loudnorm. Prints the exact filtergraph and before/after numbers.',
    usage:
      'studio audio clean-podcast --clip C [--target -16] [--presence] [--no-denoise] [--no-eq] [--no-compress] [--no-normalize]',
    example: 'studio audio clean-podcast --clip c_01',
    flags: [
      s('clip', 'clip id', true),
      n('target', 'integrated LUFS (default -16)'),
      b('presence', 'add +2 dB at 3 kHz'),
      b('no-denoise', 'skip denoise'),
      b('no-eq', 'skip EQ'),
      b('no-compress', 'skip compressor'),
      b('no-normalize', 'skip loudnorm'),
    ],
  }),
  cmd({
    name: 'audio.normalize',
    module: 'audio',
    fn: 'normalize',
    writes: true,
    summary: 'Two-pass loudness normalization of one clip.',
    usage: 'studio audio normalize --clip C [--target -14] [--tp -1.5]',
    example: 'studio audio normalize --clip c_01 --target -16',
    flags: [
      s('clip', 'clip id', true),
      n('target', 'integrated LUFS (default -14)'),
      n('tp', 'true-peak ceiling dBTP (default -1.5)'),
    ],
  }),
  cmd({
    name: 'audio.duck',
    module: 'audio',
    fn: 'duck',
    writes: true,
    summary:
      'Duck a music clip under a voice track with a sidechain compressor; also sets the music bed about 20 dB under the voice.',
    usage:
      'studio audio duck --clip MUSIC --by VOICE_TRACK [--reduction 15] [--ratio 8] [--attack 20] [--release 400] [--music-offset-db -20] [--no-level]',
    example: 'studio audio duck --clip c_music --by t_a1',
    flags: [
      s('clip', 'music clip id', true),
      s('by', 'voice track id', true),
      n('reduction', 'target reduction under speech, dB (default 15)'),
      n('ratio', 'compression ratio (default 8)'),
      n('attack', 'attack ms (default 20)'),
      n('release', 'release ms (default 400)'),
      n('music-offset-db', 'music level relative to the voice (default -20)'),
      b('no-level', 'do not set the music level'),
    ],
  }),
  cmd({
    name: 'audio.sfx.add',
    module: 'audio',
    fn: 'sfxAdd',
    writes: true,
    summary: 'Add a music/SFX file to the local library index. A license note is required.',
    usage: 'studio audio sfx add <file> --tags a,b --license "NOTE" [--bpm N]',
    example: 'studio audio sfx add whoosh.wav --tags whoosh,transition --license "CC0"',
    flags: [
      s('tags', 'comma-separated tags'),
      s('license', 'license note, or "unknown" (required; checked by the command)'),
      n('bpm', 'tempo'),
      n('loop-start', 'loop start ms'),
      n('loop-end', 'loop end ms'),
    ],
  }),
  cmd({
    name: 'audio.sfx.search',
    module: 'audio',
    fn: 'sfxSearch',
    writes: false,
    summary: 'Search the library by file name and tags only.',
    usage: 'studio audio sfx search "<query>" [--limit N]',
    example: 'studio audio sfx search "calm piano"',
    flags: [n('limit', 'max results (default 10)')],
  }),
  cmd({
    name: 'audio.sfx.list',
    module: 'audio',
    fn: 'sfxList',
    writes: false,
    summary: 'List the library.',
    usage: 'studio audio sfx list',
    example: 'studio audio sfx list',
    flags: [],
  }),
  cmd({
    name: 'image.resize',
    module: 'image',
    fn: 'resize',
    writes: true,
    summary:
      'Resize or convert a few images. Lists the outputs. Never enlarges unless asked; strips metadata; converts to sRGB.',
    usage:
      'studio image resize <files|folders...> --width N [--height N] [--mode inside|cover|contain|fill] [--format webp]',
    example: 'studio image resize photo.jpg --width 1200 --format webp',
    flags: [
      n('width', 'target width px'),
      n('height', 'target height px'),
      {
        name: 'mode',
        type: 'string',
        desc: 'inside (default), cover, contain, fill',
        values: ['inside', 'cover', 'contain', 'fill'],
      },
      s('background', 'colour for contain and for flattening alpha, #rrggbb'),
      b('allow-enlarge', 'allow output larger than the source'),
      {
        name: 'format',
        type: 'string',
        desc: 'jpeg, webp, avif, png (default: keep jpeg/png/webp)',
        values: ['jpeg', 'webp', 'avif', 'png'],
      },
      n('quality', '1-100 (defaults: jpeg 82, webp 80, avif 50)'),
      b('sharpen', 'light unsharp after a downscale'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop (cover only)',
        values: ['attention', 'entropy'],
      },
      s('out-dir', 'output folder (default renders/images)'),
      n('concurrency', 'parallel images (default min(cores-1, 4))'),
      b('no-resume', 'reprocess everything'),
    ],
  }),
  cmd({
    name: 'image.batch',
    module: 'image',
    fn: 'batch',
    writes: true,
    summary:
      'Resize a folder of images with bounded memory, progress on stderr, and resume. Reports counts, failures, bytes, peak memory.',
    usage: 'studio image batch <folder...> --width N [--format webp] [--concurrency N]',
    example: 'studio image batch shots/ --width 1280 --format webp',
    flags: [
      n('width', 'target width px'),
      n('height', 'target height px'),
      {
        name: 'mode',
        type: 'string',
        desc: 'inside (default), cover, contain, fill',
        values: ['inside', 'cover', 'contain', 'fill'],
      },
      s('background', 'colour for contain and for flattening alpha, #rrggbb'),
      b('allow-enlarge', 'allow output larger than the source'),
      {
        name: 'format',
        type: 'string',
        desc: 'jpeg, webp, avif, png (default: keep jpeg/png/webp)',
        values: ['jpeg', 'webp', 'avif', 'png'],
      },
      n('quality', '1-100 (defaults: jpeg 82, webp 80, avif 50)'),
      b('sharpen', 'light unsharp after a downscale'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop (cover only)',
        values: ['attention', 'entropy'],
      },
      s('out-dir', 'output folder (default renders/images)'),
      n('concurrency', 'parallel images (default min(cores-1, 4))'),
      b('no-resume', 'reprocess everything'),
    ],
  }),
  cmd({
    name: 'image.convert',
    module: 'image',
    fn: 'convert',
    writes: true,
    summary: 'Convert image formats without resizing.',
    usage: 'studio image convert <files|folders...> --format webp',
    example: 'studio image convert logo.png --format webp --quality 90',
    flags: [
      n('width', 'target width px'),
      n('height', 'target height px'),
      {
        name: 'mode',
        type: 'string',
        desc: 'inside (default), cover, contain, fill',
        values: ['inside', 'cover', 'contain', 'fill'],
      },
      s('background', 'colour for contain and for flattening alpha, #rrggbb'),
      b('allow-enlarge', 'allow output larger than the source'),
      {
        name: 'format',
        type: 'string',
        desc: 'jpeg, webp, avif, png (default: keep jpeg/png/webp)',
        values: ['jpeg', 'webp', 'avif', 'png'],
      },
      n('quality', '1-100 (defaults: jpeg 82, webp 80, avif 50)'),
      b('sharpen', 'light unsharp after a downscale'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop (cover only)',
        values: ['attention', 'entropy'],
      },
      s('out-dir', 'output folder (default renders/images)'),
      n('concurrency', 'parallel images (default min(cores-1, 4))'),
      b('no-resume', 'reprocess everything'),
    ],
  }),
  cmd({
    name: 'image.bgremove',
    module: 'image',
    fn: 'bgremove',
    writes: true,
    summary:
      'Cut out the subject (U2-Net via onnxruntime). Writes a PNG with alpha and a light/dark check image to look at. Records model and license.',
    usage: 'studio image bgremove <file> [--model u2net|u2netp] [--mask-in FILE]',
    example: 'studio image bgremove portrait.jpg',
    flags: [
      s('model', 'u2net (default) or u2netp (smaller, rougher)'),
      s('mask-in', 'use this grayscale mask instead of the model (same size as the image)'),
      s('out', 'output base name'),
      { name: 'format', type: 'string', desc: 'png (default) or webp', values: ['png', 'webp'] },
      b('no-preview', 'skip the light/dark check image'),
    ],
  }),
  cmd({
    name: 'image.upscale',
    module: 'image',
    fn: 'upscale',
    writes: true,
    summary:
      'Upscale once with Real-ESRGAN (invents detail). --estimate times a small crop first. Needs a Vulkan device; a software one is slow.',
    usage: 'studio image upscale <file> [--scale 2|3|4] [--width N] [--estimate]',
    example: 'studio image upscale small.png --scale 4 --estimate',
    flags: [
      n('scale', '2, 3, or 4 (default 4)'),
      {
        name: 'model',
        type: 'string',
        desc: 'realesrgan-x4plus (photos, default), realesrgan-x4plus-anime, realesr-animevideov3',
        values: ['realesrgan-x4plus', 'realesrgan-x4plus-anime', 'realesr-animevideov3'],
      },
      n('tile', 'tile size px (default 256, lowered automatically on failure)'),
      n('width', 'resize once to this width after upscaling'),
      b('estimate', 'predict the run time from two small crops, write nothing'),
      s('out', 'output base name'),
    ],
  }),
  cmd({
    name: 'image.grade',
    module: 'image',
    fn: 'grade',
    writes: true,
    summary:
      'Colour grade: exposure, white balance, contrast, highlights/shadows, saturation, vibrance, LUT, sharpen, grain (in that order). Reports luma and clipping before and after.',
    usage:
      'studio image grade <files...> [--exposure 0.5 --contrast 10 ...] [--lut F --lut-space srgb] [--match REF] [--before-after]',
    example: 'studio image grade shot.jpg --exposure 0.4 --shadows 20 --before-after',
    flags: [
      n('exposure', 'stops, -5 to 5'),
      n('temperature', '-100 cool to 100 warm'),
      n('tint', '-100 green to 100 magenta'),
      n('contrast', '-100 to 100'),
      n('highlights', '-100 to 100'),
      n('shadows', '-100 to 100'),
      n('saturation', '-100 to 100'),
      n('vibrance', '-100 to 100'),
      s('lut', '.cube 3D LUT'),
      s('lut-space', 'colour space the LUT expects: srgb or rec709 (log LUTs are refused)'),
      n('sharpen', '0 to 3'),
      n('grain', '0 to 40 (seeded)'),
      s('match', 'reference image: match channel means to it'),
      { name: 'format', type: 'string', desc: 'png, jpeg, webp', values: ['png', 'jpeg', 'webp'] },
      n('quality', '1-100'),
      s('out-dir', 'output folder (default renders/images/graded)'),
      b('before-after', 'write a side-by-side image'),
    ],
  }),
  cmd({
    name: 'image.thumbnail',
    module: 'image',
    fn: 'thumbnail',
    writes: true,
    summary:
      'One thumbnail: background frame/photo, optional cutout subject, headline (5 words max) with a contrast-checked scrim. Writes a 168 px legibility copy and the reasons for the layout.',
    usage:
      'studio image thumbnail (--image F | --from-video V --at MS) --headline "TEXT" [--subject cutout.png] [--font F]',
    example:
      'studio image thumbnail --from-video renders/demo-v1.mp4 --at 4200 --headline "Ship it faster" --subject renders/images/me-cutout.png',
    flags: [
      s('image', 'background image'),
      s('from-video', 'take the background from this video'),
      n('at', 'frame time in ms for --from-video'),
      s('headline', 'at most 5 words', true),
      s('subject', 'cutout PNG with alpha'),
      s('font', 'font file (default: first in brand/fonts)'),
      s('palette', 'palette JSON (default brand/palette.json)'),
      {
        name: 'text-side',
        type: 'string',
        desc: 'left (default) or right',
        values: ['left', 'right'],
      },
      b('vertical', '1080x1920 instead of 1280x720'),
      {
        name: 'smart',
        type: 'string',
        desc: 'attention or entropy crop of the background',
        values: ['attention', 'entropy'],
      },
      { name: 'format', type: 'string', desc: 'jpeg (default) or png', values: ['jpeg', 'png'] },
      s('out', 'output base name'),
    ],
  }),
  cmd({
    name: 'transcribe',
    module: 'captions',
    fn: 'transcribe',
    writes: true,
    summary:
      'Transcribe speech with word timestamps (faster-whisper, VAD first). Raw output is cached read-only; an editable derived transcript is written.',
    usage:
      'studio transcribe <asset|file> [--model whisper-small] [--language en] [--out transcripts/x.json]',
    example: 'studio transcribe a_1k3f --model whisper-small',
    flags: [
      s('model', 'whisper-tiny.en | whisper-small (default) | whisper-medium'),
      s('language', 'language code; detected when omitted'),
      s('out', 'derived transcript path'),
    ],
  }),
  cmd({
    name: 'captions.build',
    module: 'captions',
    fn: 'build',
    writes: true,
    summary:
      'Build caption cues from a transcript (2 lines, 42 chars, 17 cps, 1-7 s, gaps) and check them by script.',
    usage:
      'studio captions build --transcript T [--clip c_xx] [--style clean|social|karaoke] [--clean]',
    example:
      'studio captions build --transcript transcripts/a_1k3f.whisper-small.json --style karaoke',
    flags: [
      s('transcript', 'derived transcript', true),
      s('clip', 'media clip that places the transcript on the timeline'),
      s('style', 'clean | social | karaoke'),
      s('position', 'bottom | center | top'),
      n('size-pct', 'font size as % of frame height'),
      n('words-per-cue', 'social style: words per cue (relaxes cps and min duration)'),
      n('max-chars', 'characters per line'),
      n('max-cps', 'characters per second'),
      b('clean', 'remove fillers (um, uh): clean-verbatim'),
      n('fps', 'frame rate for timing'),
      n('width', 'canvas width for the safe-zone check'),
      n('height', 'canvas height'),
      s('out', 'cue file'),
    ],
  }),
  cmd({
    name: 'captions.check',
    module: 'captions',
    fn: 'check',
    writes: false,
    summary:
      'Check a cue file against the caption limits and the safe zone (layout measured in Chromium). Exit 4 on violations.',
    usage: 'studio captions check --cues FILE [--width W --height H]',
    example: 'studio captions check --cues captions/x.clean.cues.json',
    flags: [s('cues', 'cue file', true), n('width', 'canvas width'), n('height', 'canvas height')],
  }),
  cmd({
    name: 'captions.export',
    module: 'captions',
    fn: 'exportCmd',
    writes: true,
    summary: 'Write a sidecar caption file: SRT, WebVTT, or styled ASS.',
    usage: 'studio captions export --cues FILE --format srt|vtt|ass [--out FILE]',
    example: 'studio captions export --cues captions/x.clean.cues.json --format srt',
    flags: [
      s('cues', 'cue file', true),
      s('format', 'srt (default) | vtt | ass'),
      s('out', 'output file'),
      n('width', 'ASS canvas width'),
      n('height', 'ASS canvas height'),
    ],
  }),
  cmd({
    name: 'captions.add',
    module: 'captions',
    fn: 'add',
    writes: true,
    summary:
      'Put the cues on the timeline as a burned-in caption clip (an op: validated, logged, undoable).',
    usage: 'studio captions add --cues FILE [--track t_xx]',
    example: 'studio captions add --cues captions/x.clean.cues.json',
    flags: [s('cues', 'cue file', true), s('track', 'captions track (created when omitted)')],
  }),
  cmd({
    name: 'mcp',
    module: 'mcp',
    writes: false,
    summary:
      'Run an MCP server on stdio: every command except ui and mcp is a tool, executed by the same CLI.',
    usage: 'studio mcp [--project DIR]',
    example:
      'claude mcp add studio -- node packages/cli/dist/studio.js mcp --project /path/to/project',
    flags: [],
  }),
  cmd({
    name: 'motion.templates',
    module: 'motion',
    fn: 'templates',
    writes: false,
    summary: 'List motion templates and the props each accepts (type, default, limits).',
    usage: 'studio motion templates [--comp NAME]',
    example: 'studio motion templates --comp lower-third',
    flags: [s('comp', 'show one template')],
  }),
  cmd({
    name: 'motion.scaffold',
    module: 'motion',
    fn: 'scaffold',
    writes: true,
    summary: 'Write a starting props file for a template (edit the JSON, not code).',
    usage: 'studio motion scaffold --comp NAME [--out motion/props/NAME.json]',
    example: 'studio motion scaffold --comp lower-third',
    flags: [s('comp', 'template id', true), s('out', 'props file to write')],
  }),
  cmd({
    name: 'motion.still',
    module: 'motion',
    fn: 'still',
    writes: true,
    summary:
      'Render one frame of a template or project composition clip to PNG (check before rendering video).',
    usage:
      'studio motion still (--comp NAME [--props FILE|JSON] | --clip c_xx) [--frame N | --at MS] [--checker]',
    example:
      'studio motion still --comp lower-third --props motion/props/lower-third.json --at 1500 --checker',
    flags: [
      s('comp', 'template id'),
      s('clip', 'project composition clip'),
      s('props', 'props file or JSON'),
      n('frame', 'frame number'),
      n('at', 'time in ms'),
      n('dur', 'duration ms (default: template)'),
      n('width', 'canvas width'),
      n('height', 'canvas height'),
      n('fps', 'frames per second'),
      s('out', 'output PNG'),
      b('checker', 'paint a checkerboard behind, to inspect alpha'),
    ],
  }),
  cmd({
    name: 'motion.render',
    module: 'motion',
    fn: 'render',
    writes: true,
    summary:
      'Render a template or composition clip to an alpha overlay: ProRes 4444, VP9 WebM, or PNG sequence. Cached by hash.',
    usage:
      'studio motion render (--comp NAME [--props FILE|JSON] | --clip c_xx) [--format prores4444|webm|png] [--out FILE]',
    example:
      'studio motion render --comp lower-third --props motion/props/lower-third.json --dur 4000',
    flags: [
      s('comp', 'template id'),
      s('clip', 'project composition clip'),
      s('props', 'props file or JSON'),
      n('dur', 'duration ms'),
      n('width', 'canvas width'),
      n('height', 'canvas height'),
      n('fps', 'frames per second'),
      s('format', 'prores4444 (default) | webm | png'),
      s('out', 'output file'),
      n('concurrency', 'browser pages (default: half the cores)'),
    ],
  }),
  cmd({
    name: 'models.list',
    module: 'models',
    fn: 'list',
    writes: false,
    summary: 'List models and engine binaries: installed or not, license, source.',
    usage: 'studio models list',
    example: 'studio models list',
    flags: [],
  }),
  cmd({
    name: 'models.fetch',
    module: 'models',
    fn: 'fetch',
    writes: true,
    summary: 'Download a model or engine, checking size and sha256 against models/manifest.json.',
    usage: 'studio models fetch <name...> | --all [--force]',
    example: 'studio models fetch u2net',
    flags: [b('all', 'every model in the manifest')],
  }),
  cmd({
    name: 'project.set',
    module: 'project',
    writes: true,
    summary:
      'Change the project name, canvas size, frame rate, or background (an op: validated, logged, undoable).',
    usage:
      'studio project set [--name N] [--width W] [--height H] [--fps F] [--background #RRGGBB]',
    example: 'studio project set --width 1080 --height 1920 --fps 30',
    flags: [
      s('name', 'project name'),
      n('width', 'canvas width in px'),
      n('height', 'canvas height in px'),
      n('fps', 'frames per second'),
      s('background', 'background color #RRGGBB'),
    ],
  }),
  cmd({
    name: 'project.show',
    module: 'project',
    writes: false,
    summary: 'Summarize the project (tracks, clips, assets, derived duration, undo depth).',
    usage: 'studio project show [--full]',
    example: 'studio project show',
    flags: [b('full', 'include the whole project file')],
  }),
  cmd({
    name: 'project.validate',
    module: 'project',
    writes: false,
    summary: 'Check schema and invariants; warns if the file was edited outside ops.',
    usage: 'studio project validate',
    example: 'studio project validate',
    flags: [],
  }),
  cmd({
    name: 'project.diff',
    module: 'project',
    writes: false,
    summary: 'Show the ops of one transaction (by txn or op id).',
    usage: 'studio project diff <txnId|opId>',
    example: 'studio project diff tx_ab12cd',
    flags: [],
  }),
  cmd({
    name: 'project.log',
    module: 'project',
    writes: false,
    summary: 'List recent log entries.',
    usage: 'studio project log [--limit N]',
    example: 'studio project log --limit 10',
    flags: [n('limit', 'entries to show (default 20)')],
  }),
  cmd({
    name: 'project.undo',
    module: 'project',
    writes: true,
    summary: 'Undo the last transaction(s) by applying inverse ops; logs the undo.',
    usage: 'studio project undo [--n N]',
    example: 'studio project undo --n 2',
    flags: [n('n', 'transactions to undo (default 1)')],
  }),
  cmd({
    name: 'project.redo',
    module: 'project',
    writes: true,
    summary: 'Redo undone transaction(s).',
    usage: 'studio project redo [--n N]',
    example: 'studio project redo',
    flags: [n('n', 'transactions to redo (default 1)')],
  }),
  cmd({
    name: 'ops.apply',
    module: 'ops',
    writes: true,
    summary: 'Apply a JSON batch of ops atomically (all or none). File path or - for stdin.',
    usage: 'studio ops apply <ops.json|->',
    example: 'studio ops apply ops.json --dry-run',
    flags: [s('label', 'log label')],
  }),
  cmd({
    name: 'tl.add-track',
    module: 'tl',
    writes: true,
    summary: 'Add a track.',
    usage: 'studio tl add-track --type video|audio|graphics|captions --name N',
    example: 'studio tl add-track --type video --name Screen',
    flags: [
      {
        name: 'type',
        type: 'string',
        desc: 'track type',
        required: true,
        values: ['video', 'audio', 'graphics', 'captions'],
      },
      s('name', 'track name', true),
      s('role', 'e.g. music'),
      s('id', 'explicit id'),
      n('index', 'position'),
    ],
  }),
  cmd({
    name: 'tl.add-clip',
    module: 'tl',
    writes: true,
    summary: 'Add a clip from an asset or a composition.',
    usage: 'studio tl add-clip --track t --asset a|--comp name --start MS --dur MS',
    example: 'studio tl add-clip --track t_v1 --asset a_k3f9 --start 0 --dur 8200 --src-in 12000',
    flags: [
      s('track', 'track id', true),
      s('asset', 'asset id'),
      s('comp', 'composition id'),
      n('start', 'timeline ms', true),
      n('dur', 'duration ms', true),
      n('src-in', 'source in-point ms'),
      s('props', 'JSON props for comp clips'),
      s('id', 'explicit id'),
    ],
  }),
  cmd({
    name: 'tl.move',
    module: 'tl',
    writes: true,
    summary: 'Move a clip to an absolute start (optionally another track).',
    usage: 'studio tl move --id c --start MS [--track t]',
    example: 'studio tl move --id c_01 --start 1500',
    flags: [s('id', 'clip id', true), n('start', 'timeline ms', true), s('track', 'target track')],
  }),
  cmd({
    name: 'tl.trim',
    module: 'tl',
    writes: true,
    summary: 'Set absolute start, duration, or source in-point.',
    usage: 'studio tl trim --id c [--start MS] [--dur MS] [--src-in MS]',
    example: 'studio tl trim --id c_01 --dur 4000',
    flags: [
      s('id', 'clip id', true),
      n('start', 'timeline ms'),
      n('dur', 'duration ms'),
      n('src-in', 'source in-point ms'),
    ],
  }),
  cmd({
    name: 'tl.split',
    module: 'tl',
    writes: true,
    summary: 'Split a clip at a timeline time.',
    usage: 'studio tl split --id c --at MS',
    example: 'studio tl split --id c_01 --at 3000',
    flags: [s('id', 'clip id', true), n('at', 'timeline ms', true)],
  }),
  cmd({
    name: 'tl.ripple-delete',
    module: 'tl',
    writes: true,
    summary: 'Delete a clip and close the gap.',
    usage: 'studio tl ripple-delete --id c [--scope track|all]',
    example: 'studio tl ripple-delete --id c_01 --scope all',
    flags: [
      s('id', 'clip id', true),
      { name: 'scope', type: 'string', desc: 'which tracks shift', values: ['track', 'all'] },
    ],
  }),
  cmd({
    name: 'tl.set',
    module: 'tl',
    writes: true,
    summary: 'Patch clip transform, fx, props, link, label (JSON; null removes a field).',
    usage: 'studio tl set --id c --patch JSON',
    example: `studio tl set --id c_01 --patch '{"transform":{"scale":1.2}}'`,
    flags: [s('id', 'clip id', true), s('patch', 'JSON patch', true)],
  }),
  cmd({
    name: 'tl.keyframe',
    module: 'tl',
    writes: true,
    summary: 'Set a keyframe (or delete one with --delete).',
    usage:
      'studio tl keyframe --clip c --prop scale --t MS --v N [--ease expo.inOut] | --clip c --delete k_id',
    example: 'studio tl keyframe --clip c_01 --prop scale --t 1000 --v 1.8 --ease expo.inOut',
    flags: [
      s('clip', 'clip id', true),
      s('prop', 'property name'),
      n('t', 'ms from clip start'),
      n('v', 'value'),
      s('ease', 'easing name'),
      s('delete', 'keyframe id to delete'),
    ],
  }),
  cmd({
    name: 'tl.marker',
    module: 'tl',
    writes: true,
    summary: 'Add a marker.',
    usage: 'studio tl marker --t MS --label TEXT',
    example: 'studio tl marker --t 5000 --label "Click: Save"',
    flags: [n('t', 'timeline ms', true), s('label', 'text', true)],
  }),
];
